% Create a reusable connectivity-screen timing protocol.
protocol=adaptive_optopatch.generate_screen_protocol( ...
    "PulseCount",2000, ...
    "PulseDurationMs",5, ...
    "DarkIntervalMs",[45 55], ...
    "PreDelayMs",100, ...
    "PostDelayMs",100, ...
    "RandomSeed",42);
protocol.protocol_id="connectivity_2hz";
adaptive_optopatch.save_protocol("connectivity_2hz.mat",protocol);
