% Create a reusable randomized short-term-facilitation timing protocol.
conditions=adaptive_optopatch.default_stf_conditions( ...
    "RepeatsPerCondition",100, ...
    "PulsesPerTrain",10, ...
    "PulseDurationMs",5);
protocol=adaptive_optopatch.generate_stf_protocol(conditions, ...
    "EventDarkIntervalMs",[450 550], ...
    "PreDelayMs",100, ...
    "PostDelayMs",100, ...
    "RandomSeed",1001);
protocol.protocol_id="stf_50_100hz";
adaptive_optopatch.save_protocol("stf_50_100hz.mat",protocol);
