classdef TestManifestExecution < matlab.unittest.TestCase
    %TESTMANIFESTEXECUTION The runners, against the packaged simulator.
    %   run_1p_manifest, run_2p_manifest and run_manifest consume a frozen
    %   manifest and produce acquisitions, checkpoints and an archived record.
    %   What is asserted here is the runner's own contract: that it executes
    %   what the manifest says and nothing more, that staging and stop
    %   requests leave the frozen manifest untouched, that it resumes where it
    %   stopped, and that live output needs explicit confirmation.
    %
    %   Hardware safety during those runs is deliberately NOT owned here.
    %   TestStimulationSafetyCleanup, TestOnePhotonModalityIsolation,
    %   TestDmdOwnershipAcrossAcquisition and TestDmdCalibrationIdentity each
    %   drive the same runners and assert a different guarantee about them.

    methods (Test)
        function requiresExplicitConfirmationBeforeLiveOnePhotonRun(testCase)
            manifest=struct("trials",table("1p_dmd", ...
                'VariableNames',{'stimulation_mode'}));
            testCase.verifyError(@()adaptive_optopatch.run_1p_manifest( ...
                manifest,struct,[]),"adaptive_optopatch:LiveOutputNotConfirmed");
        end

        function dryRunsAndResumesManifest(testCase)
            img=zeros(20); masks=false(20,20,1); masks(8:12,8:12,1)=true;
            metadata=struct("rig_name","Virtual_Upright", ...
                "voltage_camera",struct("serial","001125"));
            ref=adaptive_optopatch.create_reference_model(img,masks,metadata);
            targets=adaptive_optopatch.build_target_bundle(ref, ...
                "SpiralRadiusUm",1,"ParkingClearancePixels",1);
            fov=adaptive_optopatch.create_fov_state(ref);
            definition=adaptive_optopatch.generate_screen_protocol( ...
                "PulseCount",1,"ModulatorVoltage",1);
            manifest=adaptive_optopatch.build_manifest(ref,targets,definition, ...
                "Mode","2p_spiral","FovState",fov, ...
                "GuiDefaults",AoFixtures.guiDefaults());
            folder=tempname; mkdir(folder); cleanup=onCleanup(@()rmdir(folder,"s")); %#ok<NASGU>
            run=adaptive_optopatch.run_manifest(manifest,targets, ...
                "OutputDirectory",folder);
            testCase.verifyEqual(run.trials.acquisition_status,"dry_run_complete");
            run2=adaptive_optopatch.run_manifest(manifest,targets, ...
                "OutputDirectory",folder,"Resume",true);
            testCase.verifyEqual(run2.trials.acquisition_status,"dry_run_complete");
        end

        function runsSimulatedOnePhotonManifest(testCase)
            outputRoot=tempname;
            cleanup=onCleanup(@()AoFixtures.removeFolder(outputRoot)); %#ok<NASGU>
            sim=adaptive_optopatch.testing.make_simulated_luminos( ...
                "SimulationOutputRoot",outputRoot,"CameraRoi",[0 9 0 8], ...
                "LaserMode","CWP");
            laser=sim.getDevice("Laser_Device","name","488");
            protocol=AoFixtures.resolvedProtocol(adaptive_optopatch.generate_screen_protocol( ...
                "PulseCount",1,"PreDelayMs",10,"PostDelayMs",10, ...
                "ModulatorVoltage",1),"1p_dmd");
            target=struct("cell_id","cell_001","qc_pass",true, ...
                "stimulation_enabled",true,"recording_enabled",true);
            targets=struct("targets",target,"dmd_camera_masks",true(8,9,1), ...
                "canonical_roi_masks",true(8,9,1), ...
                "blank_dmd_mask",false(8,9), ...
                "reference_camera",AoFixtures.frameCameraGeometry([8 9]), ...
                "parameters",struct("blue_mask_adjustment_pixels",0));
            trials=table(1,"1p_dmd","cell_001",false,1,{protocol}, ...
                protocol.acquisition_duration_s,"sim_1p","planned","", ...
                'VariableNames',{'trial_id','stimulation_mode','target_cell_id', ...
                'is_null','target_index','pulse_schedule','acquisition_duration_s', ...
                'output_tag','acquisition_status','experiment_directory'});
            run=adaptive_optopatch.run_1p_manifest( ...
                struct("trials",trials),targets,sim, ...
                "ConfirmLiveOutput",true,"ShutterSettleTimeS",0);
            testCase.verifyTrue(run.simulation);
            testCase.verifyEqual(run.trials.acquisition_status,"completed");
            folder=run.trials.experiment_directory;
            testCase.verifyTrue(startsWith(string(folder),string(outputRoot)));
            saved=load(fullfile(folder,"output_data.mat"));
            testCase.verifyTrue(saved.simulation);
            testCase.verifyTrue(saved.adaptive_optopatch_record.simulation);
            testCase.verifyEqual(saved.adaptive_optopatch_record.obis_mode,"CWP");
            testCase.verifyEqual(laser.Mode,"CWP", ...
                "The 1P runner must preserve the Luminos-owned OBIS mode.");
            executed=sim.AcquisitionHistory.wfm_data.ao;
            mod488=executed(string({executed.name})=="mod488");
            testCase.verifyEqual(string(mod488.wavefile), ...
                "adaptive_optopatch.luminos_event_waveform");
            testCase.verifyEqual(mod488.params{3},1);
            testCase.verifyEqual(numel(sim.AcquisitionHistory),1);
        end

        function runsContinuousSimulatedRoundRobinAcquisition(testCase)
            outputRoot=tempname;
            cleanup=onCleanup(@()AoFixtures.removeFolder(outputRoot)); %#ok<NASGU>
            [fovState,~]=AoFixtures.fovState();
            for k=1:3
                fovState=adaptive_optopatch.update_cell_calibration(fovState, ...
                    compose("cell_%03d",k),"CommandVoltageV",0.6+0.2*k);
            end
            protocol=adaptive_optopatch.generate_round_robin_protocol( ...
                "PulsesPerCell",2,"RandomSeed",17,"DarkIntervalMs",[20 20]);
            targets=adaptive_optopatch.build_target_bundle(fovState.reference, ...
                "SpiralRadiusUm",2,"ParkingClearancePixels",1, ...
                "BlueMaskAdjustmentPixels",0);
            manifest=adaptive_optopatch.build_manifest(fovState.reference,targets, ...
                protocol,"Mode","1p_dmd","FovState",fovState, ...
                "GuiDefaults",AoFixtures.guiDefaults());
            frozen=manifest.trials.pulse_schedule{1};
            expectedPlan=adaptive_optopatch.build_dmd_sequence_plan(frozen,targets);
            sim=adaptive_optopatch.testing.make_simulated_luminos( ...
                "SimulationOutputRoot",outputRoot, ...
                "CameraRoi",targets.reference_camera.roi);
            run=adaptive_optopatch.run_1p_manifest(manifest,targets,sim, ...
                "ConfirmLiveOutput",true,"ShutterSettleTimeS",0);
            testCase.verifyEqual(height(run.trials),1);
            testCase.verifyEqual(run.trials.acquisition_status,"completed");
            testCase.verifyEqual(numel(sim.AcquisitionHistory),1);
            dmd=sim.getDevice("DMD","name","DMD_Blue");
            testCase.verifyEqual(dmd.slot_write_count,expectedPlan.unique_mask_count);
            saved=load(fullfile(run.trials.experiment_directory,"output_data.mat"), ...
                "adaptive_optopatch_record");
            realized=saved.adaptive_optopatch_record.realized_pulses;
            testCase.verifyEqual(realized.target_cell_id,frozen.events.target_cell_id);
            testCase.verifyEqual(realized.command_voltage_v,frozen.events.command_voltage_v);
            testCase.verifyEqual(realized.dmd_pattern_index, ...
                manifest.trials.pulse_schedule{1}.events.dmd_pattern_index);
            sequence=saved.adaptive_optopatch_record.waveform_summary.dmd_sequence;
            testCase.verifyEqual(sequence.dmd_trigger_s, ...
                [0;frozen.events.offset_s(1:end-1)]);
            testCase.verifyEqual(numel(sequence.dmd_trigger_s),height(frozen.events));
        end

        function runsSimulatedBlockedTwoPhotonManifest(testCase)
            outputRoot=tempname;
            cleanup=onCleanup(@()AoFixtures.removeFolder(outputRoot)); %#ok<NASGU>
            sim=adaptive_optopatch.testing.make_simulated_luminos( ...
                "SimulationOutputRoot",outputRoot);
            definition=adaptive_optopatch.generate_screen_protocol( ...
                "PulseCount",1,"PulseDurationMs",5, ...
                "PreDelayMs",100,"PostDelayMs",100,"ModulatorVoltage",1);
            protocol=AoFixtures.resolvedProtocol(definition,"2p_spiral");
            target=struct("cell_id","cell_001","qc_pass",true,"spiral_center_xy",[1024 1024], ...
                "spiral_radius_pixels",10,"spiral_density_points_per_volt",20, ...
                "parking_point_xy",[1080 1024], ...
                "spiral_preview_center_xy",[1024 1024], ...
                "parking_preview_point_xy",[1080 1024]);
            targets=struct("schema_version","2.0.0", ...
                "coordinate_space","voltage_camera_full_sensor_pixels", ...
                "reference_camera",AoFixtures.frameCameraGeometry([2048 2048]), ...
                "targets",target);
            trials=table(1,"2p_spiral","cell_001",false,1,{protocol}, ...
                protocol.acquisition_duration_s,"sim_2p","planned","", ...
                'VariableNames',{'trial_id','stimulation_mode','target_cell_id', ...
                'is_null','target_index','pulse_schedule','acquisition_duration_s', ...
                'output_tag','acquisition_status','experiment_directory'});
            blueDmd=sim.getDevice("DMD","name","DMD_Blue");
            blueDmd.Target=true(blueDmd.Dimensions);
            run=adaptive_optopatch.run_2p_manifest( ...
                struct("trials",trials),targets,sim, ...
                "ReleaseLevel","blocked_test","ConfirmTrajectoryTest",true);
            testCase.verifyTrue(run.simulation);
            testCase.verifyEqual(run.trials.acquisition_status,"completed");
            folder=run.trials.experiment_directory;
            saved=load(fullfile(folder,"output_data.mat"));
            feedback=load(fullfile(folder,"adaptive_optopatch_2p_waveforms.mat"), ...
                "galvo_feedback");
            testCase.verifyTrue(saved.simulation);
            testCase.verifyTrue(saved.adaptive_optopatch_record.simulation);
            testCase.verifyTrue(feedback.galvo_feedback.simulated);
            testCase.verifyTrue(feedback.galvo_feedback.passed);
            testCase.verifyFalse(any(blueDmd.Target,"all"));
            testCase.verifyGreaterThan(blueDmd.StaticWriteCount,0);
            blueShutter=sim.getDevice("NI_DAQ_Shutter","name","shutter488");
            testCase.verifyFalse(blueShutter.State);
        end

        function runsAllSimulatedTwoPhotonAcquisitionsWithoutStopRequest(testCase)
            [trials,targets,sim]=AoFixtures.twoPhotonTrials(2,tempname);
            cleanup=onCleanup(@()AoFixtures.removeFolder(sim.SimulationOutputRoot)); %#ok<NASGU>
            run=adaptive_optopatch.run_2p_manifest( ...
                struct("trials",trials),targets,sim,"ReleaseLevel","standard");
            testCase.verifyEqual(run.trials.acquisition_status, ...
                repmat("completed",2,1));
        end

        function stopsTwoPhotonManifestAfterCurrentAcquisitionAndResumes(testCase)
            outputDirectory=tempname; mkdir(outputDirectory);
            cleanup=onCleanup(@()AoFixtures.removeFolder(outputDirectory)); %#ok<NASGU>
            [trials,targets,sim]=AoFixtures.twoPhotonTrials(3,tempname);
            cleanup2=onCleanup(@()AoFixtures.removeFolder(sim.SimulationOutputRoot)); %#ok<NASGU>
            stopRequested=@()true;
            run=adaptive_optopatch.run_2p_manifest( ...
                struct("trials",trials),targets,sim,"ReleaseLevel","standard", ...
                "OutputDirectory",outputDirectory,"StopRequestedFcn",stopRequested);
            testCase.verifyEqual(run.trials.acquisition_status(1),"completed");
            testCase.verifyEqual(run.trials.acquisition_status(2:3), ...
                repmat("planned",2,1));
            testCase.verifyEqual(run.trials.pulse_schedule(2:3), ...
                trials.pulse_schedule(2:3));

            resumed=adaptive_optopatch.run_2p_manifest( ...
                struct("trials",trials),targets,sim,"ReleaseLevel","standard", ...
                "OutputDirectory",outputDirectory,"Resume",true);
            testCase.verifyEqual(resumed.trials.acquisition_status, ...
                repmat("completed",3,1));
        end

        function stagedTwoPhotonRunLeavesFrozenManifestUnchanged(testCase)
            outputDirectory=tempname; mkdir(outputDirectory);
            cleanup=onCleanup(@()AoFixtures.removeFolder(outputDirectory)); %#ok<NASGU>
            [trials,targets,sim]=AoFixtures.twoPhotonTrials(2,tempname);
            cleanup2=onCleanup(@()AoFixtures.removeFolder(sim.SimulationOutputRoot)); %#ok<NASGU>
            definition=adaptive_optopatch.generate_screen_protocol( ...
                "PulseCount",4,"PulseDurationMs",5,"DarkIntervalMs",[50 50], ...
                "PreDelayMs",100,"PostDelayMs",100,"ModulatorVoltage",1);
            protocol=AoFixtures.resolvedProtocol(definition,"2p_spiral");
            trials.pulse_schedule=repmat({protocol},height(trials),1);
            trials.acquisition_duration_s(:)=protocol.acquisition_duration_s;
            manifest=struct("trials",trials);
            frozen=manifest;

            run=adaptive_optopatch.run_2p_manifest(manifest,targets,sim, ...
                "ReleaseLevel","blocked_test","ConfirmTrajectoryTest",true, ...
                "TestPulseCount",2,"OutputDirectory",outputDirectory);

            testCase.verifyEqual(manifest,frozen, ...
                "Staged execution must not mutate the frozen manifest.");
            testCase.verifyEqual(height(run.trials),height(frozen.trials));
            testCase.verifyEqual(run.trials.pulse_schedule,frozen.trials.pulse_schedule, ...
                "The archived pulse schedules must survive a staged run unchanged.");
            testCase.verifyEqual(run.trials.output_tag,frozen.trials.output_tag);
            testCase.verifyEqual(run.trials.acquisition_duration_s, ...
                frozen.trials.acquisition_duration_s);
            testCase.verifyTrue(run.staging.staged);
            testCase.verifyEqual(run.staging.source_trial_index,1);
            testCase.verifyEqual(run.staging.executed_event_count,2);
            executed=run.trials.executed_pulse_schedule{1};
            testCase.verifyEqual(height(executed.events),2);
            testCase.verifyEqual(height(frozen.trials.pulse_schedule{1}.events),4);

            % Commissioning execution state stays out of the experimental
            % run's own checkpoint, so a staged test never marks a real
            % acquisition complete.
            testCase.verifyTrue(isfile(fullfile(outputDirectory, ...
                "run_2p_checkpoint_blocked_test.mat")));
            testCase.verifyFalse(isfile(fullfile(outputDirectory, ...
                "run_2p_checkpoint.mat")));
        end

        function attenuatedTestExecutesTheExplicitPockelsCommand(testCase)
            [trials,targets,sim]=AoFixtures.twoPhotonTrials(1,tempname);
            cleanup=onCleanup(@()AoFixtures.removeFolder(sim.SimulationOutputRoot)); %#ok<NASGU>
            frozenVoltage=trials.pulse_schedule{1}.events.command_voltage_v(1);
            testCase.verifyEqual(frozenVoltage,1);

            run=adaptive_optopatch.run_2p_manifest( ...
                struct("trials",trials),targets,sim, ...
                "ReleaseLevel","attenuated_test","ConfirmTrajectoryTest",true, ...
                "ConfirmLiveOutput",true,"ModulatorVoltageOverride",0.2);
            testCase.verifyEqual(run.trials.acquisition_status,"completed");

            executed=run.trials.executed_pulse_schedule{1};
            testCase.verifyEqual(executed.events.command_voltage_v,0.2);
            testCase.verifyEqual(run.trials.pulse_schedule{1}.events.command_voltage_v, ...
                frozenVoltage,"The frozen schedule must keep its own command.");

            saved=load(fullfile(run.trials.experiment_directory, ...
                "adaptive_optopatch_2p_waveforms.mat"),"actual_waveforms");
            pockels=saved.actual_waveforms.pockels_v;
            testCase.verifyEqual(max(pockels),0.2,"AbsTol",1e-12, ...
                "The physical Pockels command must equal the confirmed test voltage.");

            record=load(fullfile(run.trials.experiment_directory, ...
                "output_data.mat"),"adaptive_optopatch_record");
            record=record.adaptive_optopatch_record;
            testCase.verifyEqual( ...
                record.frozen_pulse_schedule.events.command_voltage_v,frozenVoltage);
            testCase.verifyEqual(record.pulse_schedule.events.command_voltage_v,0.2);
        end

        function blockedTestStillCommandsZeroVolts(testCase)
            [trials,targets,sim]=AoFixtures.twoPhotonTrials(1,tempname);
            cleanup=onCleanup(@()AoFixtures.removeFolder(sim.SimulationOutputRoot)); %#ok<NASGU>
            run=adaptive_optopatch.run_2p_manifest( ...
                struct("trials",trials),targets,sim, ...
                "ReleaseLevel","blocked_test","ConfirmTrajectoryTest",true);
            saved=load(fullfile(run.trials.experiment_directory, ...
                "adaptive_optopatch_2p_waveforms.mat"),"actual_waveforms");
            testCase.verifyEqual(max(abs(saved.actual_waveforms.pockels_v)),0);
        end

        function realGalvoMotionLimitFailureStillFails(testCase)
            outputRoot=tempname;
            cleanup=onCleanup(@()AoFixtures.removeFolder(outputRoot)); %#ok<NASGU>
            sim=adaptive_optopatch.testing.make_simulated_luminos( ...
                "SimulationOutputRoot",outputRoot);
            definition=adaptive_optopatch.generate_screen_protocol( ...
                "PulseCount",1,"PulseDurationMs",5, ...
                "PreDelayMs",100,"PostDelayMs",100,"ModulatorVoltage",1);
            protocol=AoFixtures.resolvedProtocol(definition,"2p_spiral");
            target=struct("cell_id","cell_001","qc_pass",true,"spiral_center_xy",[1024 1024], ...
                "spiral_radius_pixels",10,"spiral_density_points_per_volt",20, ...
                "parking_point_xy",[1080 1024], ...
                "spiral_preview_center_xy",[1024 1024], ...
                "parking_preview_point_xy",[1080 1024]);
            targets=struct("schema_version","2.0.0", ...
                "coordinate_space","voltage_camera_full_sensor_pixels", ...
                "reference_camera",AoFixtures.frameCameraGeometry([2048 2048]), ...
                "targets",target);
            trials=table(1,"2p_spiral","cell_001",false,1,{protocol}, ...
                protocol.acquisition_duration_s,"sim_2p","planned","", ...
                'VariableNames',{'trial_id','stimulation_mode','target_cell_id', ...
                'is_null','target_index','pulse_schedule','acquisition_duration_s', ...
                'output_tag','acquisition_status','experiment_directory'});
            testCase.verifyError(@()adaptive_optopatch.run_2p_manifest( ...
                struct("trials",trials),targets,sim, ...
                "ReleaseLevel","blocked_test","ConfirmTrajectoryTest",true, ...
                "MaximumVelocityVPerS",1e6), ...
                "adaptive_optopatch:UnvalidatedGalvoMotionLimits");
        end
    end
end
