classdef TestBlueDmdAdvisoryPolicy < matlab.unittest.TestCase
    methods (Test)
        function overlapAndEdgeDoNotBlockOnePhotonManifest(testCase)
            [reference,targets,protocol]=fixture();
            targets.targets(1).dmd_overlap_pixels=7;
            targets.targets(1).edge_flag=true;
            targets.targets(1).blue_qc_pass=false;

            manifest=adaptive_optopatch.build_manifest( ...
                reference,targets,protocol,"Mode","1p_dmd");

            testCase.verifyEqual(height(manifest.trials),1);
            testCase.verifyEqual(manifest.trials.target_cell_id,"cell_001");
            codes=string({manifest.advisories.code});
            testCase.verifyTrue(any(codes=="blue_mask_overlap"));
            testCase.verifyTrue(any(codes=="blue_mask_near_edge"));

            report=adaptive_optopatch.preflight_trial( ...
                targets,manifest.trials(1,:), ...
                "RequireConfirmedLiveProtocol",false, ...
                "LiveProtocolConfirmed",true, ...
                "Advisories",manifest.advisories);
            testCase.verifyTrue(report.passed,strjoin(report.issues,newline));
            testCase.verifyTrue(any(contains(report.warnings,"overlaps another canonical ROI")));
            testCase.verifyTrue(any(contains(report.warnings,"near the camera ROI edge")));
        end

        function stimulationDisabledStillBlocksOnePhotonTarget(testCase)
            [reference,targets,protocol]=fixture();
            reference.cells(1).stimulation_enabled=false;
            targets.targets(1).stimulation_enabled=false;
            testCase.verifyError(@()adaptive_optopatch.build_manifest( ...
                reference,targets,protocol,"Mode","1p_dmd"), ...
                "adaptive_optopatch:NoAcceptedTargets");
        end
    end
end

function [reference,targets,protocol]=fixture()
mask=false(40,40); mask(15:24,15:24)=true;
cellRecord=struct("cell_id","cell_001", ...
    "stimulation_enabled",true,"recording_enabled",true);
reference=struct("fov_id","blue_advisory_test", ...
    "cells",cellRecord,"image_size",[40 40], ...
    "roi_masks",reshape(mask,40,40,1));
targetRecord=struct("cell_id","cell_001", ...
    "stimulation_enabled",true,"recording_enabled",true, ...
    "blue_qc_pass",true,"spiral_qc_pass",true,"qc_pass",true, ...
    "dmd_overlap_pixels",0,"edge_flag",false);
targets=struct("targets",targetRecord, ...
    "dmd_camera_masks",reshape(mask,40,40,1), ...
    "blue_camera_masks",reshape(mask,40,40,1), ...
    "blank_dmd_mask",false(40,40));
protocol=adaptive_optopatch.generate_screen_protocol( ...
    "PulseCount",1,"PulseDurationMs",10,"PreDelayMs",100, ...
    "PostDelayMs",100,"DarkIntervalMs",[90 90], ...
    "ModulatorVoltage",1);
protocol.events.target_cell_id(:)="cell_001";
protocol=adaptive_optopatch.normalize_protocol(protocol);
end
