classdef TestLuminosWaveformConfiguration < matlab.unittest.TestCase
    %TESTLUMINOSWAVEFORMCONFIGURATION What the builders put into a Luminos run.
    %   The positive contract of build_luminos_1p_waveform_config and
    %   build_luminos_2p_waveform_config: the records they add, the acquisition
    %   duration they set, the ports those records resolve to, and the
    %   commanded voltage they carry.
    %
    %   The three neighbouring suites own different questions about the same
    %   two functions, and none of them subsumes this one:
    %
    %     TestOnePhotonOutputSuppression   which outputs LEAVE a 1P run.
    %     TestWaveformOwnershipRegressions which records may not SURVIVE one.
    %     TestStimulationAccounting        an independent audit of the result.

    methods (Test)
        function injectsOnePhotonWaveformIntoActiveLuminosSettings(testCase)
            globalProps=struct("rate",200000,"total_time",1, ...
                "clock_source","Internal Dev1","trigger_source","Dev1/PFI9", ...
                "completion_trigger","None","daq_master",true);
            existing=struct("name","mod594","port","mod594", ...
                "wavefile","awfm_constant","params",{{0.1}}, ...
                "operation","Multiplication","concatTime",[]);
            replaced=struct("name","mod488","port","mod488", ...
                "wavefile","awfm_constant","params",{{0.2}}, ...
                "operation","Multiplication","concatTime",[]);
            wfm=struct("ao",[existing replaced],"do",[],"ai",[],"di",[], ...
                "ctri",[],"ao_camera_triggered",[],"do_camera_triggered",[]);
            protocol=AoFixtures.resolvedProtocol(adaptive_optopatch.generate_screen_protocol( ...
                "PulseCount",3,"ModulatorVoltage",1.5,"RandomSeed",2),"1p_dmd");
            [updatedGlobal,updatedWfm,summary]= ...
                adaptive_optopatch.build_luminos_1p_waveform_config( ...
                globalProps,wfm,protocol, ...
                adaptive_optopatch.virtual_upright_1p_profile());
            testCase.verifyEqual(updatedGlobal.total_time,protocol.acquisition_duration_s);
            % The operator's mod594 and AO's mod488, and nothing else: a 1P
            % build no longer adds galvo and Pockels constants.
            testCase.verifyEqual(numel(updatedWfm.ao),2);
            testCase.verifyTrue(any(string({updatedWfm.ao.name})=="mod594"));
            idx=find(string({updatedWfm.ao.name})=="mod488",1);
            testCase.verifyEqual(string(updatedWfm.ao(idx).wavefile), ...
                "adaptive_optopatch.luminos_event_waveform");
            params=updatedWfm.ao(idx).params;
            testCase.verifyEqual(numel(params),4);
            testCase.verifyEqual(summary.pulses.modulator_voltage,1.5*ones(3,1));
            t=(0:1/globalProps.rate:updatedGlobal.total_time-1/globalProps.rate);
            y=feval(updatedWfm.ao(idx).wavefile,t,params{:});
            testCase.verifyEqual(max(y),1.5);
            testCase.verifyEqual(y(end),0);
        end

        function injectsTwoPhotonVectorsIntoLuminosSettings(testCase)
            fs=200000; n=100;
            waveforms=struct("sample_rate_hz",fs, ...
                "x_v",linspace(0,0.1,n)',"y_v",zeros(n,1), ...
                "pockels_v",zeros(n,1),"preflight",struct("passed",true), ...
                "per_pulse",struct([]));
            globalProps=struct("rate",fs,"total_time",1, ...
                "clock_source","Internal Dev1", ...
                "trigger_source","Dev1/PFI9 Trigger Bridge","daq_master",true);
            old=struct("name","2P mod","port","2P mod", ...
                "wavefile","awfm_constant","params",{{0}}, ...
                "operation","Multiplication","concatTime",[]);
            wfm=struct("ao",old,"do",[],"ai",[],"di",[],"ctri",[], ...
                "ao_camera_triggered",[],"do_camera_triggered",[]);
            [g,w,summary]=adaptive_optopatch.build_luminos_2p_waveform_config( ...
                globalProps,wfm,waveforms);
            testCase.verifyEqual(numel(w.ao),4);
            testCase.verifyEqual(g.total_time,n/fs,"AbsTol",1e-12);
            testCase.verifyEqual(sort(string({w.ao.port})), ...
                sort(["Dev2/ao0","Dev2/ao1","2P mod","mod488"]));
            testCase.verifyEqual(summary.pockels_port,"Dev1/ao3");
        end

        function twoPhotonConfigNeutralizesOnlyOnePhotonStimulation(testCase)
            profile=adaptive_optopatch.virtual_upright_2p_profile(); fs=200000; n=50;
            globalProps=struct("rate",fs,"total_time",1, ...
                "clock_source","Internal Dev1","trigger_source","Dev1/PFI9", ...
                "daq_master",true);
            wfm=AoFixtures.emptyWaveformConfig();
            wfm.ao=[AoFixtures.constantOutput("unrelated","Dev1/ao7",4.2), ...
                AoFixtures.constantOutput("mod488",profile.inactive_one_photon.modulator.port,3.1)];
            wfm.do=[AoFixtures.constantOutput("AdaptiveOptopatch DMD trigger", ...
                profile.inactive_one_photon.dmd.trigger_port,1), ...
                AoFixtures.constantOutput("shutter488", ...
                profile.inactive_one_photon.shutter.port,1), ...
                AoFixtures.constantOutput("Orange DMD trigger","Dev1/port0/line5",1), ...
                AoFixtures.constantOutput("unrelated digital","Dev1/port0/line6",1)];
            waveforms=struct("sample_rate_hz",fs, ...
                "x_v",linspace(0,0.1,n)',"y_v",linspace(0,-0.1,n)', ...
                "pockels_v",[zeros(10,1);0.2*ones(10,1);zeros(30,1)], ...
                "preflight",struct("passed",true),"per_pulse",struct([]));
            [~,configured,summary]=adaptive_optopatch.build_luminos_2p_waveform_config( ...
                globalProps,wfm,waveforms,"Profile",profile);

            testCase.verifyEqual(constant_value(configured.ao,"mod488"), ...
                profile.inactive_one_photon.modulator.dark_v);
            testCase.verifyEqual(constant_value(configured.ao,"unrelated"),4.2);
            testCase.verifyEqual(constant_value(configured.do,"AdaptiveOptopatch DMD trigger"),0);
            testCase.verifyEqual(constant_value(configured.do,"shutter488"),0);
            testCase.verifyEqual(constant_value(configured.do,"Orange DMD trigger"),1);
            testCase.verifyEqual(constant_value(configured.do,"unrelated digital"),1);
            testCase.verifyTrue(all(ismember(["Adaptive2P_X","Adaptive2P_Y","2P mod"], ...
                string({configured.ao.name}))));
            pockels=configured.ao(string({configured.ao.name})=="2P mod");
            testCase.verifyEqual(pockels.params{2},waveforms.pockels_v);
            testCase.verifyEqual(summary.inactive_one_photon_outputs.blue_dmd_safe_static_state,"blank");
        end

        function mapsRelativeAmplitudeToPhysicalHardwareVoltage(testCase)
            definition=adaptive_optopatch.generate_screen_protocol( ...
                "PulseCount",2,"ModulatorVoltage",1);
            definition.acquisitions.events.command_voltage_v=[1;2];
            protocol=AoFixtures.resolvedProtocol(definition,"1p_dmd");
            originalTiming=protocol.events(:,["onset_s","duration_s"]);
            globalProps=struct("rate",200000,"total_time",1, ...
                "clock_source","Internal Dev1","trigger_source","Dev1/PFI9", ...
                "completion_trigger","None","daq_master",true);
            wfm=struct("ao",[],"do",[],"ai",[],"di",[],"ctri",[], ...
                "ao_camera_triggered",[],"do_camera_triggered",[]);
            [~,~,summary]=adaptive_optopatch.build_luminos_1p_waveform_config( ...
                globalProps,wfm,protocol, ...
                adaptive_optopatch.virtual_upright_1p_profile());
            testCase.verifyEqual(summary.pulses.modulator_voltage,[1;2]);
            testCase.verifyEqual(protocol.events(:,["onset_s","duration_s"]), ...
                originalTiming);
            p1=adaptive_optopatch.flatten_pulse_schedule(protocol);
            testCase.verifyEqual(p1.modulator_voltage,[1;2]);
            target=struct("spiral_center_xy",[100 90], ...
                "spiral_radius_pixels",10, ...
                "spiral_density_points_per_volt",20, ...
                "parking_point_xy",[130 90]);
            tform=affinetform2d([100 0 50;0 100 40;0 0 1]);
            twoPhotonProtocol=AoFixtures.resolvedProtocol(definition,"2p_spiral");
            waveforms=adaptive_optopatch.build_2p_trial_waveforms( ...
                twoPhotonProtocol,target,tform, ...
                "MaximumVelocityVPerS",500, ...
                "MaximumAccelerationVPerS2",1e6, ...
                "MinimumIlluminatedRadiusFraction",0.5);
            testCase.verifyTrue(any(abs(waveforms.pockels_v-1)<1e-12));
            testCase.verifyEqual(max(waveforms.pockels_v),2);
            testCase.verifyTrue(adaptive_optopatch.validate_protocol_for_mode( ...
                protocol,"1p_dmd").passed);
            testCase.verifyTrue(adaptive_optopatch.validate_protocol_for_mode( ...
                protocol,"2p_spiral").passed);
        end

        function validatesPulseIdentityTargetsAndPhysicalVoltage(testCase)
            protocol=adaptive_optopatch.generate_screen_protocol( ...
                "PulseCount",2,"ModulatorVoltage",1.1);
            duplicate=protocol;
            duplicate.acquisitions.events.pulse_id(2)= ...
                duplicate.acquisitions.events.pulse_id(1);
            testCase.verifyFalse(adaptive_optopatch.validate_protocol(duplicate).passed);
            resolved=AoFixtures.resolvedProtocol(protocol,"1p_dmd");
            invalidVoltage=resolved; invalidVoltage.events.command_voltage_v(1)=5.1;
            globalProps=struct("rate",200000,"clock_source","Internal Dev1", ...
                "trigger_source","Dev1/PFI9","daq_master",true);
            wfm=struct("ao",[],"do",[],"ai",[],"di",[],"ctri",[], ...
                "ao_camera_triggered",[],"do_camera_triggered",[]);
            testCase.verifyError(@()adaptive_optopatch.build_luminos_1p_waveform_config( ...
                globalProps,wfm,invalidVoltage,adaptive_optopatch.virtual_upright_1p_profile()), ...
                "adaptive_optopatch:InvalidProtocol");
        end
    end
end

function value=constant_value(records,name)
%CONSTANT_VALUE The voltage a named constant record holds.
record=records(string({records.name})==string(name));
value=record.params{1};
end
