% Canonical 1P SHORT-TERM PLASTICITY (STP) SCREEN.
%
% The name is STP rather than STF because the experiment measures short-term
% facilitation OR depression; which one a connection shows is the result, not
% an assumption of the design.
%
% One explicit, FOV-specific, multi-target acquisition. Every listed cell
% receives whole 5-pulse 20 Hz trains of 10 ms Blue pulses, and different
% cells are interleaved AT TRAIN GRANULARITY ONLY: one cell's complete
% P1..P5 train finishes before another cell's train begins. Pulse-level
% interleaving across ROIs (ROI1-P1, ROI2-P1, ROI1-P2, ROI2-P2, ...) is
% deliberately not produced, because repeating a millisecond-scale spike
% pairing between the same two stimulated neurons hundreds of times is an
% STDP induction protocol and would confound the short-term measurement.
%
% ---- EXPERIMENTAL DESIGN (edit these) --------------------------------------
target_cell_ids=compose("cell_%03d",(1:10)'); % Must be Stim-enabled in the FOV.
trains_per_cell=300;                          % n per pulse position P1..P5.
pulses_per_train=5;
frequency_hz=20;
pulse_duration_s=0.010;                       % Matches the Blue power-calibration ramp.
preferred_inter_train_gap_s=0.020;            % Train END to the next (different) target's P1.
minimum_same_cell_post_train_gap_s=1.000;     % Recovery after a cell's own P5 ENDS.
pre_delay_s=0.100;
post_delay_s=0.100;
% ---------------------------------------------------------------------------
%
% Blue command voltage is deliberately left unresolved here. NaN lets schema-4
% 1P resolution fall through to each cell's calibrated selected_blue_voltage_v
% in the FOV, which is the per-cell power measured with the same 10 ms pulse.
% Only set a finite value to override that calibration on purpose.
command_voltage_v=NaN;

protocol_directory=fileparts(mfilename("fullpath"));
project_directory=fileparts(protocol_directory);
addpath(project_directory,protocol_directory);
if ~exist("protocol_output_directory","var") || strlength(string(protocol_output_directory))==0
    protocol_output_directory=fullfile(protocol_directory,"generated");
end
random_seed=randi(2^31-1);
[events,scheduler_metadata]=adaptive_optopatch.generate_constrained_stp_round_robin_schedule( ...
    target_cell_ids,trains_per_cell,pulses_per_train,frequency_hz,pulse_duration_s, ...
    preferred_inter_train_gap_s,minimum_same_cell_post_train_gap_s, ...
    command_voltage_v,"PreDelayS",pre_delay_s,"RandomSeed",random_seed);
acquisition=struct("acquisition_id","stp_screen", ...
    "events",events,"parameters",struct,"event_order_realized",true, ...
    "target_repetitions",1,"post_delay_s",post_delay_s, ...
    "scheduler_metadata",scheduler_metadata);
% Voltage precedence for this protocol: event > acquisition > protocol >
% fov_cell. The GUI tier is never available for stimulation amplitude, and the
% normal path resolves at fov_cell.
sources=struct("command_voltage_v",["event","acquisition","protocol","fov_cell"]);
% multi_target_continuous, not each_stimulation_enabled_cell: the protocol owns
% the realized cross-target schedule, so AO runs ONE acquisition rather than
% repeating the whole 300-train experiment separately for every cell.
protocol=struct("schema_version","4.0.0", ...
    "artifact_type","experiment_definition", ...
    "protocol_id","stp_screen_"+random_seed, ...
    "protocol_type","stp_screen", ...
    "created_at",string(datetime("now","TimeZone","local")), ...
    "target_policy","multi_target_continuous", ...
    "event_order","randomized","random_seed",random_seed, ...
    "parameter_sources",sources,"parameters",struct, ...
    "acquisitions",acquisition);
protocol=adaptive_optopatch.normalize_protocol(protocol);
output_path=fullfile(protocol_output_directory,protocol.protocol_id+".mat");
adaptive_optopatch.save_protocol(output_path,protocol);

estimated_runtime_s=events.offset_s(end)+post_delay_s;
fprintf("Saved %s\n",output_path);
fprintf(['STP screen | %d cells | %d pulses at %g Hz | %.0f ms pulses | ' ...
    'train spans %.0f ms\n'],numel(target_cell_ids),pulses_per_train,frequency_hz, ...
    pulse_duration_s*1000,scheduler_metadata.train_duration_s*1000);
fprintf("Total trains %d | total events %d\n", ...
    scheduler_metadata.total_train_count,scheduler_metadata.total_event_count);
fprintf("Per cell: %d trains = %d pulses | n = %d at each of P1..P%d\n", ...
    trains_per_cell,trains_per_cell*pulses_per_train,trains_per_cell,pulses_per_train);
fprintf(['Inter-train gap %.0f ms preferred | same-cell recovery %.2f s after P%d end ' ...
    '(>= %.3f s train-onset interval)\n'],preferred_inter_train_gap_s*1000, ...
    minimum_same_cell_post_train_gap_s,pulses_per_train, ...
    scheduler_metadata.same_cell_minimum_train_onset_interval_s);
fprintf(['Realized train-start spacing mean %.1f ms (min %.1f, max %.1f) | ' ...
    '%d idle gaps totalling %.1f s\n'], ...
    scheduler_metadata.realized_mean_train_start_spacing_s*1000, ...
    scheduler_metadata.realized_min_train_start_spacing_s*1000, ...
    scheduler_metadata.realized_max_train_start_spacing_s*1000, ...
    scheduler_metadata.idle_gap_count,scheduler_metadata.total_idle_time_s);
fprintf("Approximate runtime %.1f s (%.2f min)\n", ...
    estimated_runtime_s,estimated_runtime_s/60);
