% Canonical 1P CONNECTIVITY SCREEN.
%
% One explicit, FOV-specific, multi-target acquisition. Every listed cell is
% stimulated with single 10 ms Blue pulses in a balanced randomized
% round-robin; while one cell is inside its recovery window the scheduler
% stimulates the others, so the acquisition stays near the preferred 20 ms
% global cadence. Adaptive Optopatch executes the realized event table
% literally and never recreates this schedule.
%
% ---- EXPERIMENTAL DESIGN (edit these) --------------------------------------
target_cell_ids=compose("cell_%03d",(1:10)'); % Must be Stim-enabled in the FOV.
pulses_per_cell=1000;                         % Set pulses_per_cell = 1500 for the higher-SNR version.
pulse_duration_s=0.010;                       % Matches the Blue power-calibration ramp.
preferred_global_spacing_s=0.020;             % Onset-to-onset cadence the scheduler tries to hold.
minimum_same_cell_post_pulse_gap_s=0.100;     % Dark time after a cell's pulse ENDS before it may fire again.
pre_delay_s=0.100;
post_delay_s=0.100;
% ---------------------------------------------------------------------------
%
% Blue command voltage is deliberately left unresolved here. NaN lets schema-4
% 1P resolution fall through to each cell's calibrated selected_blue_voltage_v
% in the FOV, which is the per-cell power measured with the same 10 ms pulse.
% Only set a finite value to override that calibration on purpose.
command_voltage_v=NaN;

protocol_directory=fileparts(mfilename("fullpath"));
project_directory=fileparts(protocol_directory);
addpath(project_directory,protocol_directory);
if ~exist("protocol_output_directory","var") || strlength(string(protocol_output_directory))==0
    protocol_output_directory=fullfile(protocol_directory,"generated");
end
random_seed=randi(2^31-1);
[events,scheduler_metadata]=adaptive_optopatch.generate_constrained_round_robin_schedule( ...
    target_cell_ids,pulses_per_cell,pulse_duration_s, ...
    preferred_global_spacing_s,minimum_same_cell_post_pulse_gap_s, ...
    command_voltage_v,"PreDelayS",pre_delay_s,"RandomSeed",random_seed);
acquisition=struct("acquisition_id","connectivity_round_robin", ...
    "events",events,"parameters",struct,"event_order_realized",true, ...
    "target_repetitions",1,"post_delay_s",post_delay_s, ...
    "scheduler_metadata",scheduler_metadata);
% Voltage precedence for this protocol: event > acquisition > protocol >
% fov_cell. The GUI tier is never available for stimulation amplitude, and the
% normal path resolves at fov_cell.
sources=struct("command_voltage_v",["event","acquisition","protocol","fov_cell"]);
protocol=struct("schema_version","4.0.0", ...
    "artifact_type","experiment_definition", ...
    "protocol_id","connectivity_round_robin_"+random_seed, ...
    "protocol_type","connectivity_round_robin", ...
    "created_at",string(datetime("now","TimeZone","local")), ...
    "target_policy","multi_target_continuous", ...
    "event_order","randomized","random_seed",random_seed, ...
    "parameter_sources",sources,"parameters",struct, ...
    "acquisitions",acquisition);
protocol=adaptive_optopatch.normalize_protocol(protocol);
output_path=fullfile(protocol_output_directory,protocol.protocol_id+".mat");
adaptive_optopatch.save_protocol(output_path,protocol);

estimated_runtime_s=events.offset_s(end)+post_delay_s;
fprintf("Saved %s\n",output_path);
fprintf(['Connectivity round robin | %d cells | %d pulses/cell | %d events | ' ...
    '%.0f ms pulses\n'],numel(target_cell_ids),pulses_per_cell,height(events), ...
    pulse_duration_s*1000);
fprintf(['Cadence %.0f ms preferred | same-cell recovery %.0f ms after pulse end ' ...
    '(>= %.0f ms onset interval)\n'],preferred_global_spacing_s*1000, ...
    minimum_same_cell_post_pulse_gap_s*1000, ...
    scheduler_metadata.same_cell_minimum_onset_interval_s*1000);
fprintf(['Realized spacing mean %.1f ms (min %.1f, max %.1f) | %d idle gaps ' ...
    'totalling %.1f s\n'],scheduler_metadata.realized_mean_event_spacing_s*1000, ...
    scheduler_metadata.realized_min_event_spacing_s*1000, ...
    scheduler_metadata.realized_max_event_spacing_s*1000, ...
    scheduler_metadata.idle_gap_count,scheduler_metadata.total_idle_time_s);
fprintf("Approximate runtime %.1f s (%.2f min)\n", ...
    estimated_runtime_s,estimated_runtime_s/60);
