% Create one explicit constrained round-robin acquisition for a FOV.

% Edit these experimental-design values here. Adaptive Optopatch executes the
% resulting event table literally; it does not recreate this schedule.
target_cell_ids=compose("cell_%03d",(1:10)');
command_voltage_v=1.0; % Shared value, or one value per target_cell_ids entry.
pulses_per_cell=1000;
pulse_duration_s=0.020;
preferred_global_spacing_s=0.020;
minimum_same_cell_post_pulse_gap_s=0.100;
pre_delay_s=0.100;
post_delay_s=0.100;

protocol_directory=fileparts(mfilename("fullpath"));
project_directory=fileparts(protocol_directory);
addpath(project_directory,protocol_directory);
if ~exist("protocol_output_directory","var") || strlength(string(protocol_output_directory))==0
    protocol_output_directory=fullfile(protocol_directory,"generated");
end
random_seed=randi(2^31-1);
[events,scheduler_metadata]=generate_constrained_round_robin_schedule( ...
    target_cell_ids,pulses_per_cell,pulse_duration_s, ...
    preferred_global_spacing_s,minimum_same_cell_post_pulse_gap_s, ...
    command_voltage_v,"PreDelayS",pre_delay_s,"RandomSeed",random_seed);
acquisition=struct("acquisition_id","round_robin", ...
    "events",events,"parameters",struct,"event_order_realized",true, ...
    "target_repetitions",1,"post_delay_s",post_delay_s, ...
    "scheduler_metadata",scheduler_metadata);
sources=struct("command_voltage_v",["event","acquisition","protocol","fov_cell"]);
protocol=struct("schema_version","3.0.0", ...
    "artifact_type","experiment_definition", ...
    "protocol_id","round_robin_"+random_seed, ...
    "protocol_type","round_robin", ...
    "created_at",string(datetime("now","TimeZone","local")), ...
    "target_policy","multi_target_continuous", ...
    "event_order","randomized","random_seed",random_seed, ...
    "parameter_sources",sources,"parameters",struct, ...
    "acquisitions",acquisition);
protocol=adaptive_optopatch.normalize_protocol(protocol);
output_path=fullfile(protocol_output_directory,protocol.protocol_id+".mat");
adaptive_optopatch.save_protocol(output_path,protocol);
estimated_runtime_s=events.offset_s(end)+post_delay_s;
fprintf("Saved %s | %d events | %.1f s (%.2f min)\n",output_path, ...
    height(events),estimated_runtime_s,estimated_runtime_s/60);
