function record=apply_galvo_calibration_to_luminos(app,value,options)
%APPLY_GALVO_CALIBRATION_TO_LUMINOS Install an accepted transform in memory.
arguments
    app
    value (1,1) struct
    options.ConfirmApply (1,1) logical = false
    options.Persist (1,1) logical = true
    options.StoreRoot (1,1) string = ""
end
if isfield(value,"calibration"), calibration=value.calibration;
else, calibration=value;
end
if ~options.ConfirmApply
    error("adaptive_optopatch:CalibrationApplyNotConfirmed", ...
        "Explicitly confirm before replacing the live scanner transform.");
end
if ~isfield(calibration,"passed") || ~calibration.passed || ...
        ~isfield(calibration,"tform")
    error("adaptive_optopatch:UnacceptedGalvoCalibration", ...
        "Only a calibration that passed fit and held-out QC can be applied.");
end
profile=adaptive_optopatch.virtual_upright_2p_profile();
artifact=struct([]);
artifactPath="";
pointerPath="";
if options.Persist
    if ~isfield(value,"camera") || ~isfield(value,"experiment_directory")
        error("adaptive_optopatch:CalibrationProvenanceRequired", ...
            "Persistent activation requires the complete calibration result.");
    end
    calibrationId=string(datetime("now","Format","yyyyMMdd_HHmmss_SSS"));
    cameraSerial=string(value.camera.serial);
    artifact=struct("schema_version","0.1.0", ...
        "calibration_id",calibrationId,"created_at", ...
        string(datetime("now","TimeZone","local")), ...
        "rig_name","Virtual_Upright","camera_serial",cameraSerial, ...
        "camera_name",string(value.camera.name), ...
        "camera_roi",value.camera.ROI,"camera_bin",value.camera.bin, ...
        "scanner_name",profile.scanner.name, ...
        "scanner_x_port",profile.scanner.x_port, ...
        "scanner_y_port",profile.scanner.y_port, ...
        "pockels_port",profile.modulator.port, ...
        "source_experiment_directory",value.experiment_directory, ...
        "calibration",calibration);
    validation=adaptive_optopatch.validate_galvo_calibration_artifact(artifact,app);
    if ~validation.passed
        error("adaptive_optopatch:CalibrationArtifactRejected","%s", ...
            strjoin(validation.issues,newline));
    end
end
scanner=app.getDevice("Scanning_Device","name",profile.scanner.name);
if numel(scanner)~=1
    error("adaptive_optopatch:ScannerNotFound", ...
        "The live Chameleon scanner was not found uniquely.");
end
oldTransform=scanner.tform;
scanner.tform=calibration.tform;
if options.Persist
    root=adaptive_optopatch.galvo_calibration_store_root("Root",options.StoreRoot);
    if ~isfolder(root), mkdir(root); end
    filename="galvo_calibration_"+artifact.calibration_id+".mat";
    artifactPath=fullfile(root,filename);
    galvo_calibration_artifact=artifact; %#ok<NASGU>
    save(artifactPath,"galvo_calibration_artifact","-v7.3");
    active_galvo_calibration=struct("schema_version","0.1.0", ...
        "activated_at",string(datetime("now","TimeZone","local")), ...
        "calibration_id",artifact.calibration_id, ...
        "artifact_filename",filename); %#ok<NASGU>
    pointerPath=fullfile(root,"active_galvo_calibration.mat");
    temporaryPointer=fullfile(root,"active_galvo_calibration.tmp.mat");
    save(temporaryPointer,"active_galvo_calibration");
    movefile(temporaryPointer,pointerPath,"f");
end
record=struct("schema_version","0.1.0","applied_at", ...
    string(datetime("now","TimeZone","local")), ...
    "scanner_name",profile.scanner.name,"previous_transform",oldTransform, ...
    "applied_transform",calibration.tform, ...
    "rmse_pixels",calibration.rmse_pixels, ...
    "held_out_rmse_pixels",calibration.held_out_rmse_pixels, ...
    "persisted",options.Persist,"artifact_path",artifactPath, ...
    "active_pointer_path",pointerPath);
end
