function targets = build_target_bundle(reference, options)
%BUILD_TARGET_BUNDLE Derive 1P soma masks and 2P spiral specifications.
arguments
    reference (1,1) struct
    options.SpiralRadiusUm (1,1) double {mustBePositive} = 6
    options.SpiralDensityPointsPerVolt (1,1) double {mustBePositive} = 10
    options.DmdErosionPixels (1,1) double {mustBeInteger} = 1
    options.EdgeMarginPixels (1,1) double {mustBeNonnegative} = 2
    options.ParkingClearancePixels (1,1) double {mustBeNonnegative} = 3
    options.ParkingMaximumDistanceSpiralDiameters (1,1) double {mustBePositive} = 2
    options.ParkingIntensityAveragingRadiusPixels (1,1) double {mustBeNonnegative,mustBeInteger} = 2
    options.PulseDurationMs (1,1) double {mustBePositive} = 5
    options.ScannerSampleRateHz (1,1) double {mustBePositive} = 200000
end

nCells = numel(reference.cells);
dmdMasks = false([reference.image_size, nCells]);
targetRows = struct([]);
allRois = any(reference.roi_masks,3);
spiralRadiusPixels=options.SpiralRadiusUm/reference.microns_per_pixel;
centers=reshape([reference.cells.camera_centroid_xy],2,[])';
parking=adaptive_optopatch.select_local_parking_points( ...
    reference.reference_image,reference.roi_masks,centers,spiralRadiusPixels, ...
    "ClearancePixels",options.ParkingClearancePixels, ...
    "MaximumDistanceSpiralDiameters",options.ParkingMaximumDistanceSpiralDiameters, ...
    "EdgeMarginPixels",options.EdgeMarginPixels, ...
    "IntensityAveragingRadiusPixels",options.ParkingIntensityAveragingRadiusPixels);
scannerTransform=[];
if isfield(reference,"scanner") && isfield(reference.scanner,"tform")
    scannerTransform=reference.scanner.tform;
end

for i = 1:nCells
    mask = reference.roi_masks(:,:,i);
    if options.DmdErosionPixels > 0
        mask = imerode(mask, strel("disk", options.DmdErosionPixels, 0));
        if ~any(mask,"all")
            mask = reference.roi_masks(:,:,i);
        end
    elseif options.DmdErosionPixels < 0
        mask = imdilate(mask,strel("disk",abs(options.DmdErosionPixels),0));
    end
    otherRois = allRois & ~reference.roi_masks(:,:,i);
    overlapPixels = nnz(mask & otherRois);
    edgeFlag = reference.cells(i).edge_distance_pixels < options.EdgeMarginPixels;
    dmdMasks(:,:,i) = mask;
    targetRecord = struct( ...
        "cell_id", reference.cells(i).cell_id, ...
        "camera_centroid_xy", reference.cells(i).camera_centroid_xy, ...
        "dmd_mask_index", i, ...
        "dmd_overlap_pixels", overlapPixels, ...
        "spiral_center_xy", reference.cells(i).camera_centroid_xy, ...
        "spiral_radius_pixels", spiralRadiusPixels, ...
        "spiral_radius_um", options.SpiralRadiusUm, ...
        "spiral_density_points_per_volt", options.SpiralDensityPointsPerVolt, ...
        "parking_point_xy", parking(i).parking_point_xy, ...
        "parking_distance_pixels", parking(i).parking_distance_pixels, ...
        "parking_clearance_pixels", parking(i).parking_clearance_pixels, ...
        "parking_mean_reference_intensity",parking(i).parking_mean_reference_intensity, ...
        "parking_search_maximum_distance_pixels", ...
            parking(i).parking_search_maximum_distance_pixels, ...
        "parking_selection_method", parking(i).parking_selection_method, ...
        "parking_qc_pass", parking(i).parking_qc_pass, ...
        "spiral_cycle_metrics", adaptive_optopatch.calculate_spiral_cycles( ...
            scannerTransform,reference.cells(i).camera_centroid_xy, ...
            spiralRadiusPixels,options.SpiralDensityPointsPerVolt, ...
            options.PulseDurationMs,"ScannerSampleRateHz",options.ScannerSampleRateHz), ...
        "edge_flag", edgeFlag, ...
        "qc_pass", overlapPixels == 0 && ~edgeFlag && parking(i).parking_qc_pass);
    if i == 1
        targetRows = targetRecord;
    else
        targetRows(i,1) = targetRecord;
    end
end

targets = struct;
targets.schema_version = "0.1.0";
targets.fov_id = reference.fov_id;
targets.coordinate_space = "voltage_camera_acquired_roi";
targets.blank_dmd_mask = false(reference.image_size);
targets.dmd_camera_masks = dmdMasks;
targets.targets = targetRows;
targets.parameters = struct( ...
    "spiral_radius_um", options.SpiralRadiusUm, ...
    "spiral_density_points_per_volt", options.SpiralDensityPointsPerVolt, ...
    "pulse_duration_ms",options.PulseDurationMs, ...
    "scanner_sample_rate_hz",options.ScannerSampleRateHz, ...
    "parking_clearance_pixels",options.ParkingClearancePixels, ...
    "parking_maximum_distance_spiral_diameters", ...
        options.ParkingMaximumDistanceSpiralDiameters, ...
    "parking_intensity_averaging_radius_pixels", ...
        options.ParkingIntensityAveragingRadiusPixels, ...
    "dmd_erosion_pixels", options.DmdErosionPixels, ...
    "edge_margin_pixels", options.EdgeMarginPixels);
end
