function preview=build_2p_plan_preview(protocol,target,hardware,options)
%BUILD_2P_PLAN_PREVIEW Shared guarded 2P preview used by both runner GUIs.
arguments
    protocol (1,1) struct
    target (1,1) struct
    hardware (1,1) struct
    options.ReleaseLevel (1,1) string = "blocked_test"
    options.MaximumVelocityVPerS (1,1) double {mustBePositive} = 1000
    options.MaximumAccelerationVPerS2 (1,1) double {mustBePositive} = 6e6
    options.AllowCalibrationExtrapolation (1,1) logical = false
end
motion=adaptive_optopatch.validate_provisional_2p_motion_limits( ...
    options.MaximumVelocityVPerS,options.MaximumAccelerationVPerS2);
if ~motion.passed
    error("adaptive_optopatch:UnvalidatedGalvoMotionLimits", ...
        "%s",strjoin(motion.issues,newline));
end
coverage=adaptive_optopatch.validate_2p_calibration_coverage( ...
    target,hardware.calibration);
if ~coverage.passed && ~options.AllowCalibrationExtrapolation
    error("adaptive_optopatch:TargetOutsideGalvoCalibration", ...
        "The target lies outside the accepted calibration hull. " + ...
        "Enable calibration extrapolation to proceed. Details: %s", ...
        strjoin(coverage.issues," "));
end
minimumRadiusFraction=0.95;
if options.ReleaseLevel=="blocked_test", minimumRadiusFraction=eps; end
waveforms=adaptive_optopatch.build_2p_trial_waveforms( ...
    protocol,target,hardware.scanner.tform, ...
    "MaximumVelocityVPerS",options.MaximumVelocityVPerS, ...
    "MaximumAccelerationVPerS2",options.MaximumAccelerationVPerS2, ...
    "MinimumIlluminatedRadiusFraction",minimumRadiusFraction);
preview=struct("schema_version","0.1.0","waveforms",waveforms, ...
    "calibration_coverage",coverage,"motion_validation",motion);
end
