function [globalProps,wfmData,summary]=build_luminos_2p_waveform_config( ...
        activeGlobalProps,activeWfmData,waveforms,options)
%BUILD_LUMINOS_2P_WAVEFORM_CONFIG Inject validated X/Y/Pockels sample vectors.
arguments
    activeGlobalProps (1,1) struct
    activeWfmData (1,1) struct
    waveforms (1,1) struct
    options.Profile (1,1) struct = adaptive_optopatch.virtual_upright_2p_profile()
end
profile=options.Profile;
required=["rate","clock_source","trigger_source","daq_master"];
if ~all(isfield(activeGlobalProps,required))
    error("adaptive_optopatch:IncompleteActiveWaveformSettings", ...
        "The active Luminos waveform lacks rate, clock, trigger, or DAQ-master settings.");
end
if abs(double(activeGlobalProps.rate)-waveforms.sample_rate_hz)>1e-9
    error("adaptive_optopatch:TwoPhotonSampleRateMismatch", ...
        "Planned 2P waveforms are at %.0f Hz but Luminos is configured for %.0f Hz.", ...
        waveforms.sample_rate_hz,double(activeGlobalProps.rate));
end
n=numel(waveforms.x_v);
if numel(waveforms.y_v)~=n || numel(waveforms.pockels_v)~=n
    error("adaptive_optopatch:TwoPhotonWaveformSizeMismatch", ...
        "Galvo X, galvo Y, and Pockels vectors must have equal lengths.");
end
globalProps=activeGlobalProps;
globalProps.total_time=n/waveforms.sample_rate_hz;
wfmData=ensure_fields(activeWfmData);
wfmData=neutralize_one_photon_outputs(wfmData,profile.inactive_one_photon);
wfmData.ao=remove_outputs(wfmData.ao, ...
    [profile.scanner.x_port profile.scanner.y_port ...
     profile.modulator.name profile.modulator.port]);
wfmData.ao=append_record(wfmData.ao,make_record( ...
    "Adaptive2P_X",profile.scanner.x_port,waveforms.sample_rate_hz, ...
    waveforms.x_v,waveforms.x_v(end)));
wfmData.ao=append_record(wfmData.ao,make_record( ...
    "Adaptive2P_Y",profile.scanner.y_port,waveforms.sample_rate_hz, ...
    waveforms.y_v,waveforms.y_v(end)));
wfmData.ao=append_record(wfmData.ao,make_record( ...
    profile.modulator.name,profile.modulator.name,waveforms.sample_rate_hz, ...
    waveforms.pockels_v,profile.modulator.dark_v));
summary=struct("schema_version","0.1.0", ...
    "sample_rate_hz",waveforms.sample_rate_hz,"sample_count",n, ...
    "duration_s",globalProps.total_time, ...
    "clock_source",reshape(string(globalProps.clock_source),1,[]), ...
    "trigger_source",reshape(string(globalProps.trigger_source),1,[]), ...
    "x_port",profile.scanner.x_port,"y_port",profile.scanner.y_port, ...
    "pockels_port",profile.modulator.port, ...
    "preflight",waveforms.preflight,"per_pulse",waveforms.per_pulse, ...
    "requested_acquisition_duration_s",optional_field( ...
        waveforms,"requested_acquisition_duration_s",globalProps.total_time), ...
    "actual_acquisition_duration_s",optional_field( ...
        waveforms,"actual_acquisition_duration_s",globalProps.total_time), ...
    "automatic_extension_s",optional_field(waveforms,"automatic_extension_s",0), ...
    "inactive_one_photon_outputs",struct( ...
        "mod488_port",string(profile.inactive_one_photon.modulator.port), ...
        "mod488_dark_v",double(profile.inactive_one_photon.modulator.dark_v), ...
        "blue_dmd_trigger_port",string(profile.inactive_one_photon.dmd.trigger_port), ...
        "blue_dmd_trigger_safe_state",logical(profile.inactive_one_photon.dmd.trigger_safe_state), ...
        "blue_dmd_safe_static_state",string(profile.inactive_one_photon.dmd.safe_static_state), ...
        "shutter488_port",string(profile.inactive_one_photon.shutter.port), ...
        "shutter488_closed_state",logical(profile.inactive_one_photon.shutter.closed_state), ...
        "safe_value_source",string(profile.inactive_one_photon.safe_value_source)));
end

function data=neutralize_one_photon_outputs(data,outputs)
modulator=outputs.modulator; dmd=outputs.dmd;
data.ao=remove_outputs(data.ao,[modulator.name modulator.port]);
data.ao=append_record(data.ao,constant_record( ...
    modulator.name,modulator.name,modulator.dark_v));
data.do=remove_outputs(data.do,[dmd.trigger_name dmd.trigger_alias dmd.trigger_port]);
data.do=append_record(data.do,constant_record( ...
    dmd.trigger_name,dmd.trigger_port,dmd.trigger_safe_state));
shutter=outputs.shutter;
data.do=remove_outputs(data.do,[shutter.name shutter.port]);
data.do=append_record(data.do,constant_record( ...
    shutter.name,shutter.port,shutter.closed_state));
end

function record=constant_record(name,port,value)
record=struct("name",char(name),"port",char(port), ...
    "wavefile","awfm_constant","params",{{double(value)}}, ...
    "operation","Multiplication","concatTime",[]);
end

function value=optional_field(data,name,defaultValue)
if isfield(data,name), value=data.(name); else, value=defaultValue; end
end

function record=make_record(name,port,sampleRate,values,finalValue)
record=struct("name",char(name),"port",char(port), ...
    "wavefile","adaptive_optopatch.luminos_sampled_waveform", ...
    "params",{{sampleRate,values(:),finalValue}}, ...
    "operation","Multiplication","concatTime",[]);
end

function data=ensure_fields(data)
for name=["ao","do","ai","di","ctri","ao_camera_triggered","do_camera_triggered"]
    if ~isfield(data,name), data.(name)=[]; end
end
end

function values=remove_outputs(values,identifiers)
if isempty(values), return; end
keep=true(size(values));
identifiers=strip(string(identifiers));
for k=1:numel(values)
    name=""; port="";
    if isfield(values,"name"), name=strip(string(values(k).name)); end
    if isfield(values,"port"), port=strip(string(values(k).port)); end
    keep(k)=~any(name==identifiers | port==identifiers);
end
values=values(keep);
end

function values=append_record(values,record)
if isempty(values), values=record; return; end
fields=union(fieldnames(values),fieldnames(record),'stable');
for k=1:numel(fields)
    if ~isfield(values,fields{k}), [values.(fields{k})]=deal([]); end
    if ~isfield(record,fields{k}), record.(fields{k})=[]; end
end
values(end+1)=orderfields(record,values);
end
