function calibration=fit_galvo_camera_calibration(galvoVolts,cameraPixels,options)
%FIT_GALVO_CAMERA_CALIBRATION Fit and QC galvo-volts -> camera-pixels affine map.
arguments
    galvoVolts (:,2) double
    cameraPixels (:,2) double
    options.CommandBoundsV (1,2) double = [-5 5]
    options.MaximumRmsePixels (1,1) double {mustBePositive} = 2
end
if size(galvoVolts,1)~=size(cameraPixels,1) || size(galvoVolts,1)<6
    error("adaptive_optopatch:InsufficientCalibrationPoints", ...
        "At least six paired galvo-voltage and camera-pixel points are required.");
end
if any(~isfinite(galvoVolts),"all") || any(~isfinite(cameraPixels),"all")
    error("adaptive_optopatch:InvalidCalibrationPoints", ...
        "Calibration points must be finite.");
end
if any(galvoVolts<options.CommandBoundsV(1) | ...
        galvoVolts>options.CommandBoundsV(2),"all")
    error("adaptive_optopatch:CalibrationVoltageOutsideBounds", ...
        "A calibration command lies outside the configured scanner range.");
end
design=[galvoVolts ones(size(galvoVolts,1),1)];
if rank(design)<3
    error("adaptive_optopatch:DegenerateCalibrationGeometry", ...
        "Calibration voltages must span two dimensions.");
end
coefficients=design\cameraPixels;
tform=affinetform2d(coefficients');
predicted=transformPointsForward(tform,galvoVolts);
residuals=predicted-cameraPixels;
rmse=sqrt(mean(sum(residuals.^2,2)));
maximumError=max(vecnorm(residuals,2,2));
heldOutPredicted=nan(size(cameraPixels));
for k=1:size(galvoVolts,1)
    keep=true(size(galvoVolts,1),1); keep(k)=false;
    heldOutCoefficients=design(keep,:)\cameraPixels(keep,:);
    heldOutPredicted(k,:)=[galvoVolts(k,:) 1]*heldOutCoefficients;
end
heldOutResiduals=heldOutPredicted-cameraPixels;
heldOutRmse=sqrt(mean(sum(heldOutResiduals.^2,2)));
passed=rmse<=options.MaximumRmsePixels && ...
    heldOutRmse<=options.MaximumRmsePixels;
issues=strings(0,1);
if ~passed
    issues(end+1)=sprintf( ...
        "Calibration RMSE %.3f px exceeds the %.3f px limit.", ...
        rmse,options.MaximumRmsePixels);
end
if heldOutRmse>options.MaximumRmsePixels
    issues(end+1)=sprintf( ...
        "Held-out RMSE %.3f px exceeds the %.3f px limit.", ...
        heldOutRmse,options.MaximumRmsePixels);
end
calibration=struct("schema_version","0.1.0", ...
    "created_at",string(datetime("now","TimeZone","local")), ...
    "transform_direction","galvo_volts_to_camera_pixels", ...
    "tform",tform,"galvo_volts",galvoVolts, ...
    "camera_pixels",cameraPixels,"predicted_camera_pixels",predicted, ...
    "residuals_pixels",residuals,"rmse_pixels",rmse, ...
    "maximum_error_pixels",maximumError, ...
    "held_out_predicted_camera_pixels",heldOutPredicted, ...
    "held_out_residuals_pixels",heldOutResiduals, ...
    "held_out_rmse_pixels",heldOutRmse, ...
    "command_bounds_v",options.CommandBoundsV, ...
    "maximum_allowed_rmse_pixels",options.MaximumRmsePixels, ...
    "passed",passed,"issues",issues);
end
