function protocol=generate_single_cell_ramp_protocol(voltageLevelsV,options)
%GENERATE_SINGLE_CELL_RAMP_PROTOCOL Build an ROI-independent ordered ramp.
arguments
    voltageLevelsV (1,:) double
    options.RepeatsPerVoltage (1,1) double {mustBePositive,mustBeInteger} = 10
    options.PulseDurationMs (1,1) double {mustBePositive} = 10
    options.DarkIntervalMs (1,1) double {mustBeNonnegative} = 90
    options.PreDelayMs (1,1) double {mustBeNonnegative} = 100
    options.PostDelayMs (1,1) double {mustBeNonnegative} = 100
    options.RandomSeed (1,1) double {mustBeNonnegative,mustBeInteger} = 1
end
if isempty(voltageLevelsV) || any(~isfinite(voltageLevelsV) | ...
        voltageLevelsV<=0 | voltageLevelsV>5)
    error("adaptive_optopatch:InvalidRampVoltages", ...
        "VoltageLevelsV must contain positive finite voltages no greater than 5 V.");
end
levels=double(voltageLevelsV(:)); nLevels=numel(levels);
commandVoltageV=repelem(levels,options.RepeatsPerVoltage);
levelIndex=repelem((1:nLevels)',options.RepeatsPerVoltage);
repeatIndex=repmat((1:options.RepeatsPerVoltage)',nLevels,1);
n=numel(commandVoltageV); pulseId=(1:n)';
conditionId="voltage_"+replace(compose("%.4gV",commandVoltageV),".","p");
onsetS=(options.PreDelayMs+(0:n-1)'* ...
    (options.PulseDurationMs+options.DarkIntervalMs))/1000;
durationS=repmat(options.PulseDurationMs/1000,n,1); isNull=false(n,1);
blueMaskAdjustmentPixels=nan(n,1);
events=table(pulseId,conditionId,onsetS,durationS,isNull, ...
    commandVoltageV,blueMaskAdjustmentPixels,levelIndex,repeatIndex, ...
    'VariableNames',{'pulse_id','condition_id','onset_s','duration_s', ...
    'is_null','command_voltage_v','blue_mask_adjustment_pixels', ...
    'voltage_level_index','repeat_index'});
acquisition=struct("acquisition_id","voltage_ramp", ...
    "events",events,"parameters",struct, ...
    "event_order_realized",true,"target_repetitions",1, ...
    "acquisition_duration_s",max(onsetS+durationS)+options.PostDelayMs/1000);
protocol=struct("schema_version","3.0.0", ...
    "artifact_type","experiment_definition", ...
    "protocol_id","single_cell_blue_ramp", ...
    "protocol_type","single_cell_blue_ramp", ...
    "created_at",string(datetime("now","TimeZone","local")), ...
    "target_policy","each_stimulation_enabled_cell", ...
    "event_order","ordered","random_seed",options.RandomSeed, ...
    "parameters",struct,"acquisitions",acquisition);
protocol=adaptive_optopatch.normalize_protocol(protocol);
end
