function protocol=generate_connectivity_chunked_protocol(targetCellIds,options)
%GENERATE_CONNECTIVITY_CHUNKED_PROTOCOL Explicit reproducible 1P chunks.
arguments
    targetCellIds (:,1) string
    options.TotalPulsesPerCell (1,1) double {mustBePositive,mustBeInteger} = 1000
    options.PulsesPerCellPerChunk (1,1) double {mustBePositive,mustBeInteger} = 100
    options.PulseDurationS (1,1) double {mustBePositive} = 0.010
    options.PreferredGlobalSpacingS (1,1) double {mustBePositive} = 0.020
    options.MinimumSameCellPostPulseGapS (1,1) double {mustBeNonnegative} = 0.100
    options.PreDelayS (1,1) double {mustBeNonnegative} = 0.100
    options.PostDelayS (1,1) double {mustBeNonnegative} = 0.100
    options.BaseRandomSeed (1,1) double {mustBeNonnegative,mustBeInteger} = 3001
    options.CommandVoltageV double = NaN
    options.FlutMaxEntries (1,1) double {mustBePositive,mustBeInteger} = 4096
end
if mod(options.TotalPulsesPerCell,options.PulsesPerCellPerChunk)~=0
    error("adaptive_optopatch:ConnectivityChunkSizeNotDivisible", ...
        "total_pulses_per_cell must be exactly divisible by pulses_per_cell_per_chunk.");
end
chunkCount=options.TotalPulsesPerCell/options.PulsesPerCellPerChunk;
eventCount=numel(targetCellIds)*options.PulsesPerCellPerChunk;
capacity=adaptive_optopatch.calculate_dmd_flut_playlist_capacity( ...
    options.FlutMaxEntries,numel(targetCellIds));
if eventCount>capacity
    error("adaptive_optopatch:ConnectivityChunkExceedsFlutCapacity", ...
        "Each connectivity chunk contains %d events for %d targets, but the " + ...
         "executable FLUT playlist capacity is %d. Reduce " + ...
         "pulses_per_cell_per_chunk.",eventCount,numel(targetCellIds),capacity);
end

acquisitionCells=cell(chunkCount,1);
for chunkIndex=1:chunkCount
    seed=options.BaseRandomSeed+chunkIndex-1;
    conditionId=sprintf("connectivity_round_robin_chunk_%02d",chunkIndex);
    [events,metadata]=adaptive_optopatch.generate_constrained_round_robin_schedule( ...
        targetCellIds,options.PulsesPerCellPerChunk,options.PulseDurationS, ...
        options.PreferredGlobalSpacingS,options.MinimumSameCellPostPulseGapS, ...
        options.CommandVoltageV,"PreDelayS",options.PreDelayS, ...
        "ConditionId",conditionId,"RandomSeed",seed);
    metadata.chunk_index=chunkIndex;
    metadata.chunk_count=chunkCount;
    metadata.total_pulses_per_cell=options.TotalPulsesPerCell;
    metadata.pulses_per_cell_per_chunk=options.PulsesPerCellPerChunk;
    metadata.flut=struct("event_count",height(events), ...
        "unique_mask_upper_bound",numel(targetCellIds), ...
        "playlist_capacity",capacity,"valid",true);
    acquisitionCells{chunkIndex}=struct( ...
        "acquisition_id",string(conditionId),"events",events, ...
        "parameters",struct,"event_order_realized",true, ...
        "target_repetitions",1,"post_delay_s",options.PostDelayS, ...
        "scheduler_metadata",metadata);
end
acquisitions=vertcat(acquisitionCells{:});

sources=struct("command_voltage_v",["event","acquisition","protocol","fov_cell"]);
protocol=struct("schema_version","4.0.0", ...
    "artifact_type","experiment_definition", ...
    "protocol_id","connectivity_round_robin_chunks_"+options.BaseRandomSeed, ...
    "protocol_type","connectivity_round_robin", ...
    "created_at",string(datetime("now","TimeZone","local")), ...
    "target_policy","multi_target_continuous", ...
    "event_order","randomized","random_seed",options.BaseRandomSeed, ...
    "parameter_sources",sources,"parameters",struct, ...
    "acquisitions",acquisitions);
protocol=adaptive_optopatch.normalize_protocol(protocol);
end
