function protocol=generate_blue_mask_titration_protocol(adjustments,options)
%GENERATE_BLUE_MASK_TITRATION_PROTOCOL Define randomized per-cell mask tests.
arguments
    adjustments (1,:) double {mustBeInteger}
    options.RepeatsPerAdjustment (1,1) double {mustBePositive,mustBeInteger} = 1
    options.PulseDurationMs (1,1) double {mustBePositive} = 10
    options.DarkIntervalMs (1,1) double {mustBeNonnegative} = 90
    options.PreDelayMs (1,1) double {mustBeNonnegative} = 100
    options.PostDelayMs (1,1) double {mustBeNonnegative} = 100
    options.EventOrder (1,1) string {mustBeMember(options.EventOrder,["ordered","randomized"])} = "randomized"
    options.RandomSeed (1,1) double {mustBeNonnegative,mustBeInteger} = 2001
end
if isempty(adjustments)
    error("adaptive_optopatch:InvalidBlueMaskAdjustments", ...
        "Provide at least one Blue-mask adjustment.");
end
values=repelem(double(adjustments(:)),options.RepeatsPerAdjustment);
repeatIndex=repmat((1:options.RepeatsPerAdjustment)',numel(adjustments),1);
if options.EventOrder=="randomized"
    stream=RandStream("mt19937ar","Seed",options.RandomSeed);
    order=randperm(stream,numel(values)); values=values(order); repeatIndex=repeatIndex(order);
end
n=numel(values); pulseId=(1:n)';
conditionId="blue_mask_"+string(values); onsetS=(options.PreDelayMs+ ...
    (0:n-1)'*(options.PulseDurationMs+options.DarkIntervalMs))/1000;
durationS=repmat(options.PulseDurationMs/1000,n,1); isNull=false(n,1);
commandVoltageV=nan(n,1); blueMaskAdjustmentPixels=values;
events=table(pulseId,conditionId,onsetS,durationS,isNull, ...
    commandVoltageV,blueMaskAdjustmentPixels,repeatIndex, ...
    'VariableNames',{'pulse_id','condition_id','onset_s','duration_s', ...
    'is_null','command_voltage_v','blue_mask_adjustment_pixels','repeat_index'});
acquisition=struct("acquisition_id","blue_mask_titration", ...
    "events",events,"parameters",struct, ...
    "event_order_realized",true,"target_repetitions",1, ...
    "acquisition_duration_s",max(onsetS+durationS)+options.PostDelayMs/1000);
sources=struct("command_voltage_v",["event","acquisition","protocol","fov_cell"]);
protocol=struct("schema_version","3.0.0", ...
    "artifact_type","experiment_definition", ...
    "protocol_id","blue_mask_titration_seed_"+options.RandomSeed, ...
    "protocol_type","blue_dmd_mask_titration", ...
    "created_at",string(datetime("now","TimeZone","local")), ...
    "target_policy","each_stimulation_enabled_cell", ...
    "event_order",options.EventOrder,"random_seed",options.RandomSeed, ...
    "parameter_sources",sources,"parameters",struct, ...
    "acquisitions",acquisition);
protocol=adaptive_optopatch.normalize_protocol(protocol);
end
