function protocol=generate_round_robin_protocol(options)
%GENERATE_ROUND_ROBIN_PROTOCOL Define an ROI-independent continuous sequence.
arguments
    options.PulsesPerCell (1,1) double {mustBePositive,mustBeInteger} = 100
    options.PulseDurationMs (1,1) double {mustBePositive} = 10
    options.DarkIntervalMs (1,2) double {mustBeNonnegative} = [90 110]
    options.PreDelayMs (1,1) double {mustBeNonnegative} = 100
    options.PostDelayMs (1,1) double {mustBeNonnegative} = 100
    options.EventOrder (1,1) string {mustBeMember(options.EventOrder,["ordered","randomized"])} = "randomized"
    options.RandomSeed (1,1) double {mustBeNonnegative,mustBeInteger} = 3001
end
if options.DarkIntervalMs(2)<options.DarkIntervalMs(1)
    error("adaptive_optopatch:InvalidDarkInterval","DarkIntervalMs must be [minimum maximum].");
end
pulseId=1; conditionId="round_robin"; onsetS=NaN;
durationS=options.PulseDurationMs/1000; isNull=false;
commandVoltageV=NaN; blueMaskAdjustmentPixels=NaN;
events=table(pulseId,conditionId,onsetS,durationS,isNull, ...
    commandVoltageV,blueMaskAdjustmentPixels, ...
    'VariableNames',{'pulse_id','condition_id','onset_s','duration_s', ...
    'is_null','command_voltage_v','blue_mask_adjustment_pixels'});
sequence=struct("pre_delay_s",options.PreDelayMs/1000, ...
    "dark_interval_range_s",options.DarkIntervalMs/1000);
acquisition=struct("acquisition_id","round_robin", ...
    "events",events,"parameters",struct, ...
    "event_order_realized",false, ...
    "target_repetitions",options.PulsesPerCell,"sequence",sequence, ...
    "post_delay_s",options.PostDelayMs/1000);
sources=struct("command_voltage_v",["event","acquisition","protocol","fov_cell"]);
protocol=struct("schema_version","3.0.0", ...
    "artifact_type","experiment_definition", ...
    "protocol_id","round_robin_seed_"+options.RandomSeed, ...
    "protocol_type","round_robin", ...
    "created_at",string(datetime("now","TimeZone","local")), ...
    "target_policy","multi_target_continuous", ...
    "event_order",options.EventOrder,"random_seed",options.RandomSeed, ...
    "parameter_sources",sources,"parameters",struct, ...
    "acquisitions",acquisition);
protocol=adaptive_optopatch.normalize_protocol(protocol);
end
