function plan=generate_galvo_calibration_waveforms(options)
%GENERATE_GALVO_CALIBRATION_WAVEFORMS Safe step-and-image voltage grid.
arguments
    options.CenterV (1,2) double = [0 0]
    options.HalfRangeV (1,1) double {mustBePositive} = 0.1
    options.GridSize (1,1) double {mustBeInteger,mustBeGreaterThanOrEqual(options.GridSize,3)} = 3
    options.SampleRateHz (1,1) double {mustBePositive} = 200000
    options.CameraFrameRateHz (1,1) double {mustBePositive} = 20
    options.SettleTimeMs (1,1) double {mustBeNonnegative} = 30
    options.FramesPerPoint (1,1) double {mustBePositive,mustBeInteger} = 4
    options.PockelsVoltage (1,1) double {mustBeGreaterThanOrEqual(options.PockelsVoltage,0),mustBeLessThanOrEqual(options.PockelsVoltage,5)} = 0
    options.MaximumVelocityVPerS (1,1) double {mustBePositive} = 1000
    options.MaximumAccelerationVPerS2 (1,1) double {mustBePositive} = 6e6
    options.CommandBoundsV (1,2) double = [-5 5]
    options.PreDelayMs (1,1) double {mustBeNonnegative} = 100
    options.PostDelayMs (1,1) double {mustBeNonnegative} = 100
end
if mod(options.GridSize,2)==0
    error("adaptive_optopatch:OddCalibrationGridRequired", ...
        "Use an odd grid size so that the center voltage is sampled.");
end
axisValues=linspace(-options.HalfRangeV,options.HalfRangeV,options.GridSize);
grid=zeros(options.GridSize^2,2); q=0;
for row=1:options.GridSize
    xs=axisValues;
    if mod(row,2)==0, xs=fliplr(xs); end
    for x=xs
        q=q+1; grid(q,:)=options.CenterV+[x axisValues(row)];
    end
end
if any(grid<options.CommandBoundsV(1) | grid>options.CommandBoundsV(2),"all")
    error("adaptive_optopatch:CalibrationGridOutsideBounds", ...
        "The requested calibration grid exceeds scanner command bounds.");
end
fs=options.SampleRateHz;
x=repmat(options.CenterV(1),round(options.PreDelayMs/1000*fs),1);
y=repmat(options.CenterV(2),size(x));
pockels=zeros(size(x));
records=repmat(struct("point_index",0,"galvo_x_v",0,"galvo_y_v",0, ...
    "illumination_onset_s",0,"illumination_offset_s",0, ...
    "expected_frame_indices",[]),size(grid,1),1);
current=options.CenterV;
nSettle=round(options.SettleTimeMs/1000*fs);
nLight=ceil(options.FramesPerPoint/options.CameraFrameRateHz*fs);
for k=1:size(grid,1)
    move=adaptive_optopatch.minimum_jerk_transition(current,grid(k,:),fs, ...
        "MaximumVelocityVPerS",options.MaximumVelocityVPerS, ...
        "MaximumAccelerationVPerS2",options.MaximumAccelerationVPerS2);
    % Do not duplicate the first sample already held by the preceding segment.
    if size(move,1)>1, move=move(2:end,:); end
    x=[x;move(:,1);repmat(grid(k,1),nSettle+nLight,1)]; %#ok<AGROW>
    y=[y;move(:,2);repmat(grid(k,2),nSettle+nLight,1)]; %#ok<AGROW>
    pockels=[pockels;zeros(size(move,1)+nSettle,1); ...
        repmat(options.PockelsVoltage,nLight,1)]; %#ok<AGROW>
    lightOn=(numel(x)-nLight)/fs;
    lightOff=numel(x)/fs;
    frameTimes=(0:ceil(lightOff*options.CameraFrameRateHz)+2)/ ...
        options.CameraFrameRateHz;
    frameIndices=find(frameTimes>=lightOn & frameTimes<lightOff);
    records(k)=struct("point_index",k,"galvo_x_v",grid(k,1), ...
        "galvo_y_v",grid(k,2),"illumination_onset_s",lightOn, ...
        "illumination_offset_s",lightOff, ...
        "expected_frame_indices",frameIndices(:));
    current=grid(k,:);
end
move=adaptive_optopatch.minimum_jerk_transition(current,options.CenterV,fs, ...
    "MaximumVelocityVPerS",options.MaximumVelocityVPerS, ...
    "MaximumAccelerationVPerS2",options.MaximumAccelerationVPerS2);
if size(move,1)>1, move=move(2:end,:); end
x=[x;move(:,1);repmat(options.CenterV(1),round(options.PostDelayMs/1000*fs),1)];
y=[y;move(:,2);repmat(options.CenterV(2),round(options.PostDelayMs/1000*fs),1)];
pockels=[pockels;zeros(size(move,1)+round(options.PostDelayMs/1000*fs),1)];
preflight=adaptive_optopatch.evaluate_galvo_waveform(x,y,fs, ...
    "CommandBoundsVolts",options.CommandBoundsV, ...
    "MaximumVelocityVPerS",options.MaximumVelocityVPerS, ...
    "MaximumAccelerationVPerS2",options.MaximumAccelerationVPerS2, ...
    "CheckRepetitionRate",false);
if ~preflight.passed
    error("adaptive_optopatch:GalvoCalibrationPreflightFailed","%s", ...
        strjoin(preflight.issues,newline));
end
plan=struct("schema_version","0.1.0","created_at", ...
    string(datetime("now","TimeZone","local")), ...
    "sample_rate_hz",fs,"camera_frame_rate_hz",options.CameraFrameRateHz, ...
    "x_v",x,"y_v",y,"pockels_v",pockels, ...
    "duration_s",numel(x)/fs,"grid_volts",grid,"points",records, ...
    "center_v",options.CenterV,"half_range_v",options.HalfRangeV, ...
    "grid_size",options.GridSize,"settle_time_ms",options.SettleTimeMs, ...
    "frames_per_point",options.FramesPerPoint, ...
    "pockels_voltage",options.PockelsVoltage, ...
    "maximum_velocity_v_per_s",options.MaximumVelocityVPerS, ...
    "maximum_acceleration_v_per_s2",options.MaximumAccelerationVPerS2, ...
    "preflight",preflight,"per_pulse",struct([]));
end
