function metadata=protocol_parameter_metadata()
%PROTOCOL_PARAMETER_METADATA Central parameter scope and fallback metadata.
metadata=struct( ...
    "name",{"command_voltage_v","pulse_duration_s", ...
    "blue_mask_adjustment_pixels","orange_expansion_pixels", ...
    "spiral_radius_um","spiral_density_points_per_volt"}, ...
    "scope",{"event","event","event","acquisition","acquisition","acquisition"}, ...
    "event_field",{"command_voltage_v","duration_s", ...
    "blue_mask_adjustment_pixels","","",""}, ...
    "fov_cell_field",{"selected_blue_voltage_v","pulse_duration_s", ...
    "blue_mask_adjustment_pixels","orange_expansion_pixels", ...
    "spiral_radius_um","spiral_density_points_per_volt"}, ...
    "gui_field",{"command_voltage_v","pulse_duration_s", ...
    "blue_mask_adjustment_pixels","orange_expansion_pixels", ...
    "spiral_radius_um","spiral_density_points_per_volt"});
end
