function run=run_mixed_manifest(manifest,targets,app,options)
%RUN_MIXED_MANIFEST Unified production entry point for schema-4 events.
arguments
    manifest (1,1) struct
    targets (1,1) struct
    app
    options.OutputDirectory (1,1) string = ""
    options.OutputRoot (1,1) string = ""
    options.Resume (1,1) logical = true
    options.StopAfterTrial (1,1) double {mustBeNonnegative,mustBeInteger} = 0
    options.ConfirmLiveOutput (1,1) logical = false
    options.ConfirmTrajectoryTest (1,1) logical = false
    options.ReleaseLevel (1,1) string = "standard"
    options.LaserPowerW (1,1) double = NaN
    options.MaximumVelocityVPerS (1,1) double {mustBePositive} = 1000
    options.MaximumAccelerationVPerS2 (1,1) double {mustBePositive} = 6e6
    options.AllowCalibrationExtrapolation (1,1) logical = false
    options.AllowCameraRateOverride (1,1) logical = false
    options.StopRequestedFcn = []
    options.ScannerCalibration struct = struct([])
    options.ModulatorVoltageOverride (1,1) double = NaN
    options.StimulationAccountingPolicy (1,1) string = "report_only"
end
has1p=cellfun(@(p)any(p.events.stimulation_source=="1p_dmd"), ...
    manifest.trials.pulse_schedule);
has2p=cellfun(@(p)any(p.events.stimulation_source=="2p_spiral"), ...
    manifest.trials.pulse_schedule);
if any(has1p)
    run=adaptive_optopatch.run_1p_manifest(manifest,targets,app, ...
        "OutputDirectory",options.OutputDirectory,"OutputRoot",options.OutputRoot, ...
        "Resume",options.Resume,"StopAfterTrial",options.StopAfterTrial, ...
        "ConfirmLiveOutput",options.ConfirmLiveOutput,"LaserPowerW",options.LaserPowerW, ...
        "AllowMixedSources",any(has2p),"ScannerCalibration",options.ScannerCalibration, ...
        "MaximumVelocityVPerS",options.MaximumVelocityVPerS, ...
        "MaximumAccelerationVPerS2",options.MaximumAccelerationVPerS2, ...
        "AllowCameraRateOverride",options.AllowCameraRateOverride, ...
        "TwoPhotonReleaseLevel",options.ReleaseLevel, ...
        "TwoPhotonVoltageOverride",options.ModulatorVoltageOverride, ...
        "StopRequestedFcn",options.StopRequestedFcn, ...
        "StimulationAccountingPolicy",options.StimulationAccountingPolicy);
else
    run=adaptive_optopatch.run_2p_manifest(manifest,targets,app, ...
        "ReleaseLevel",options.ReleaseLevel, ...
        "OutputDirectory",options.OutputDirectory,"OutputRoot",options.OutputRoot, ...
        "Resume",options.Resume,"StopAfterTrial",options.StopAfterTrial, ...
        "ConfirmTrajectoryTest",options.ConfirmTrajectoryTest, ...
        "ConfirmLiveOutput",options.ConfirmLiveOutput, ...
        "MaximumVelocityVPerS",options.MaximumVelocityVPerS, ...
        "MaximumAccelerationVPerS2",options.MaximumAccelerationVPerS2, ...
        "AllowCalibrationExtrapolation",options.AllowCalibrationExtrapolation, ...
        "AllowCameraRateOverride",options.AllowCameraRateOverride, ...
        "StopRequestedFcn",options.StopRequestedFcn, ...
        "ScannerCalibration",options.ScannerCalibration, ...
        "StimulationAccountingPolicy",options.StimulationAccountingPolicy);
end
end
