function summary=summarize_protocol(value)
%SUMMARIZE_PROTOCOL Return compact read-only protocol information.
report=adaptive_optopatch.validate_protocol(value);
if ~report.passed
    error("adaptive_optopatch:InvalidProtocol","%s",strjoin(report.issues,newline));
end
protocol=report.protocol; events=protocol.events;
light=~events.is_null;
totalLightOn=sum(events.duration_s(light));
summary=struct("schema_version","2.0.0", ...
    "protocol_type",string(protocol.protocol_type), ...
    "protocol_id",string(protocol.protocol_id), ...
    "event_count",height(events),"light_event_count",sum(light), ...
    "condition_count",numel(unique(string(events.condition_id))), ...
    "duration_range_s",[min(events.duration_s) max(events.duration_s)], ...
    "first_event_s",min(events.onset_s), ...
    "last_event_s",max(events.onset_s+events.duration_s), ...
    "acquisition_duration_s",double(protocol.acquisition_duration_s), ...
    "total_light_on_s",totalLightOn, ...
    "random_seed",protocol.random_seed);
end
