function profile = virtual_upright_1p_profile()
%VIRTUAL_UPRIGHT_1P_PROFILE Declared Luminos hardware for blue-DMD stimulation.
% Physical wiring and live device properties are checked again before output.

profile = struct;
profile.schema_version = "0.2.0";
profile.profile_id = "virtual_upright_488_dmd_blue";
profile.rig_name = "Virtual_Upright";
profile.source = "src/Applications/Virtual_Upright/Virtual_Upright.json";
profile.daq = struct("name","Dev1", ...
    "default_clock","Internal Dev1", ...
    "supported_internal_masters",["Dev1","Dev2"], ...
    "synchronization_branch","VU_MultiDAQ_Synchronization", ...
    "requires_self_trigger",true);
profile.daq.default_trigger=["Dev1/PFI9","Dev2/PFI1"];
profile.daq.clock_bridge=["Dev1/PFI12","Dev2/PFI0"];
profile.camera = struct("name","Orca Fusion", ...
    "serial","001125", ...
    "clock","Dev1/PFI0", ...
    "hsync_rate_hz",200000, ...
    "trigger","Dev1/port0/line3");
profile.dmd = struct("name","DMD_Blue", ...
    "device_type","ALP_DMD");
profile.laser = struct("name","488", ...
    "device_type","OBIS_Laser", ...
    "com_port","COM9", ...
    "wavelength_nm",488, ...
    "max_power_w",0.055, ...
    "external_modulation_modes",["ANALOG","MIXED"]);
profile.modulator = struct("name","mod488", ...
    "device_type","NI_DAQ_Modulator", ...
    "port","Dev1/ao2", ...
    "minimum_v",0, ...
    "maximum_v",5, ...
    "dark_v",0);
profile.shutter = struct("name","shutter488", ...
    "device_type","NI_DAQ_Shutter", ...
    "port","Dev1/port0/line0", ...
    "closed_state",false, ...
    "open_state",true);
end
