function manifest=virtual_upright_stimulation_manifest()
%VIRTUAL_UPRIGHT_STIMULATION_MANIFEST Declared VU stimulation outputs and neutrals.
%   One explicit statement of every physical output on the Virtual Upright
%   that adaptive_optopatch is allowed to command, what its neutral value
%   is, and who owns it at run time. Terminals AO deliberately does not own
%   are declared too, with the reason, because "AO does not own it" is not
%   a classification: it does not say whether a waveform found there is
%   expected imaging infrastructure or an unexplained stimulation record.
%
%   Everything here is transcribed from the rig file
%
%       luminos-private/src/Applications/Virtual_Upright/Virtual_Upright.json
%
%   and, for the neutral values, from the two existing rig safety profiles.
%   The neutral values are READ from those profiles rather than restated,
%   so this manifest consolidates the safety declaration that was split
%   across virtual_upright_1p_profile.inactive_two_photon and
%   virtual_upright_2p_profile.inactive_one_photon without becoming a
%   second, drifting copy of it. A neutral value is a rig safety
%   declaration; nothing in this package may infer that zero is safe.
%
%   See also CANONICAL_TERMINAL, ACCOUNT_STIMULATION_OUTPUTS,
%   NEUTRALIZE_ALL_STIMULATION.

oneP=adaptive_optopatch.virtual_upright_1p_profile();
twoP=adaptive_optopatch.virtual_upright_2p_profile();

manifest=struct;
manifest.schema_version="1.0.0";
manifest.rig_name="Virtual_Upright";
manifest.source="luminos-private/src/Applications/Virtual_Upright/Virtual_Upright.json";
manifest.script_owner=adaptive_optopatch.script_owner_tag();

% DAQ.alias_list as the rig file's alias_init parses into it: column 1 the
% actual terminal, column 2 the alias, in declaration order. Transcribed so
% that a pure waveform builder, holding structs and no DAQ object, resolves
% terminals exactly as the live DAQ will.
manifest.alias_list={ ...
    "Dev1/PFI0","Dev1/PFI0 Camera Clock Input"; ...
    "Dev1/PFI9","Dev1/PFI9 Trigger Bridge"; ...
    "Dev2/PFI1","Dev2/PFI1 Trigger Bridge"; ...
    "Dev1/PFI12","Dev1/PFI12 Clock Bridge"; ...
    "Dev2/PFI0","Dev2/PFI0 Clock Bridge"; ...
    "Dev1/ao3","2P mod"; ...
    "Dev1/ao2","mod488"; ...
    "Dev1/ao1","mod594"; ...
    "Dev1/port0/line0","shutter488"; ...
    "Dev1/port0/line1","shutter594"; ...
    "Dev1/port0/line2","Shutter sensory"; ...
    "Dev1/port0/line4","DMD Trigger"; ...
    "Dev1/port0/line5","General Shutter"; ...
    "Dev1/port0/line3","Cam1 Trigger"; ...
    "Dev1/port0/line7","Cam2 Trigger"};

% ---------------------------------------------------------------------
% Outputs adaptive_optopatch owns and may command
% ---------------------------------------------------------------------
% owner says who drives the line while an acquisition is armed, and it is
% stated per modality because for one line the answer genuinely differs:
%   "buffered"   the installed wfm_data record is the sole runtime owner
%   "imperative" AO's own device writes are the sole runtime owner, and no
%                buffered record for the line may be installed at all
% The two are never both true for one line in one acquisition. That is the
% ownership invariant the 1P shutter488 hazard violated, and accounting
% checks it against this declaration rather than against a rule of thumb.
manifest.outputs=[ ...
    output("blue_modulator",oneP.modulator.name,oneP.modulator.port, ...
        "mod488","ao",double(oneP.modulator.dark_v), ...
        "virtual_upright_1p_profile.modulator.dark_v",owner("buffered","buffered"), ...
        "488 nm intensity command. Carries the whole 1P pulse train."); ...
    output("blue_shutter",oneP.shutter.name,oneP.shutter.port, ...
        "shutter488","do",double(oneP.shutter.closed_state), ...
        "virtual_upright_1p_profile.shutter.closed_state", ...
        owner("imperative","buffered"), ...
        ["Mechanical 488 nm shutter. A 1P run opens it before arming and " ...
         "closes it after, so no buffered record may own this line during " ...
         "a 1P acquisition. A 2P run installs the declared closed constant " ...
         "instead and makes no imperative write while the task is armed."]); ...
    output("blue_dmd_advance_trigger",twoP.inactive_one_photon.dmd.trigger_name, ...
        oneP.dmd.trigger_port,oneP.dmd.trigger_alias,"do", ...
        double(twoP.inactive_one_photon.dmd.trigger_safe_state), ...
        "virtual_upright_2p_profile.inactive_one_photon.dmd.trigger_safe_state", ...
        owner("buffered","buffered"), ...
        ["Advances the Blue DMD pattern stack on the rising edge. A stale " ...
         "record stored under the rig alias combines with AO's train and " ...
         "advances the stack to the wrong cell."]); ...
    output("two_photon_modulator",twoP.modulator.name,twoP.modulator.port, ...
        "2P mod","ao",double(twoP.modulator.dark_v), ...
        "virtual_upright_2p_profile.modulator.dark_v",owner("buffered","buffered"), ...
        "Pockels cell command. Carries the whole 2P intensity envelope."); ...
    output("galvo_x",twoP.scanner.name,twoP.scanner.x_port, ...
        strings(1,0),"ao", ...
        double(oneP.inactive_two_photon.scanner.stationary_v(1)), ...
        "virtual_upright_1p_profile.inactive_two_photon.scanner.stationary_v(1)", ...
        owner("buffered","buffered"),"Chameleon scan mirror X command."); ...
    output("galvo_y",twoP.scanner.name,twoP.scanner.y_port, ...
        strings(1,0),"ao", ...
        double(oneP.inactive_two_photon.scanner.stationary_v(2)), ...
        "virtual_upright_1p_profile.inactive_two_photon.scanner.stationary_v(2)", ...
        owner("buffered","buffered"),"Chameleon scan mirror Y command.")];

% ---------------------------------------------------------------------
% Non-stimulation infrastructure AO deliberately inherits
% ---------------------------------------------------------------------
% AO does not clear the operator's Waveforms configuration: it still runs
% inside a Luminos acquisition and still depends on the operator's imaging
% illumination. These are the terminals a waveform is EXPECTED on, with the
% reason it is expected, so that finding one there is not a surprise and
% finding a waveform anywhere else still is.
manifest.inherited=[ ...
    inherited("orange_modulator","mod594","Dev1/ao1","mod594","ao", ...
        ["594 nm recording illumination. AO records voltage with the " ...
         "operator's own orange imaging configuration and never commands " ...
         "it; its waveform is part of the acquisition AO was asked to run."]); ...
    inherited("orange_shutter","shutter594","Dev1/port0/line1","shutter594","do", ...
        "Mechanical 594 nm shutter, gated with mod594 by the operator.")];

% ---------------------------------------------------------------------
% Infrastructure Luminos itself adds at acquisition time
% ---------------------------------------------------------------------
% Setup_Camera_Trigger_Waveforms appends a DO record on each master
% camera's trigger line after AO has installed wfm_data, tagged
% script_owner='camera_trigger'. Accounting inspects the CANDIDATE
% configuration, so these are normally absent from what it sees; they are
% declared anyway because a record found on one of them is expected rather
% than unaccounted.
manifest.luminos_infrastructure=[ ...
    infrastructure("camera_1_trigger","Orca Fusion","Dev1/port0/line3", ...
        "Cam1 Trigger","do", ...
        "Camera 1 frame trigger, added by Setup_Camera_Trigger_Waveforms."); ...
    infrastructure("camera_2_trigger","Orca Fusion 2","Dev1/port0/line7", ...
        "Cam2 Trigger","do", ...
        "Camera 2 frame trigger, added by Setup_Camera_Trigger_Waveforms.")];

% ---------------------------------------------------------------------
% Declared by the rig, NOT yet classified
% ---------------------------------------------------------------------
% These exist in the rig file and AO cannot honestly say what they do. They
% are listed so the accounting report can name them and quote what the rig
% says, rather than inventing a classification that would make a test pass
% and a real rig unsafe. Accounting reports them as unaccounted; Pass 3A
% runs report-only precisely so a VU session can resolve them.
manifest.unresolved=[ ...
    unresolved("pmt_shutter","PMT Shutter","Dev2/ao2",strings(1,0),"ao", ...
        ["Rig declares Voltage_Shutter 'PMT Shutter' on Dev2/ao2 with " ...
         "offVoltage 0 and onVoltage 0.7. It gates the PMT rather than the " ...
         "specimen, so it is probably not stimulation-capable - but it is " ...
         "an analog output on the galvo card whose neutral AO has never " ...
         "declared, and 0 V here is the rig's off value rather than an " ...
         "assumption. Confirm on the VU whether AO must hold it."]); ...
    unresolved("general_shutter","General Shutter","Dev1/port0/line5", ...
        "General Shutter","do", ...
        ["Rig declares NI_DAQ_Shutter 'General Shutter' on Dev1/port0/line5, " ...
         "aliased 'General Shutter'. AO's own test fixtures have long " ...
         "called this line 'Orange DMD trigger', and the rig file declares " ...
         "no trigger terminal for DMD_Orange at all. One of those two " ...
         "readings is wrong. If line5 advances the Orange DMD it is " ...
         "imaging infrastructure; if it is a beam shutter it may be " ...
         "stimulation-capable. Resolve on the VU before fail_closed."]); ...
    unresolved("sensory_shutter","Shutter sensory","Dev1/port0/line2", ...
        "Shutter sensory","do", ...
        ["Rig declares NI_DAQ_Shutter 'Shutter sensory' on Dev1/port0/line2. " ...
         "The name suggests a sensory-stimulation shutter, which would make " ...
         "it stimulation-capable and therefore AO's concern during an " ...
         "optogenetics run. AO has never commanded it and must not assume " ...
         "it is inert."]); ...
    unresolved("orange_dmd_advance_trigger","DMD_Orange","", ...
        strings(1,0),"do", ...
        ["The rig file gives DMD_Orange no trigger terminal, so AO cannot " ...
         "name the line that advances it. If the Orange DMD is advanced " ...
         "from a DO line on this rig, that line is currently unaccounted " ...
         "and needs adding here."])];
end

function record=output(role,deviceName,terminal,aliases,kind,neutralValue, ...
        neutralSource,runtimeOwner,reason)
record=base_record(role,deviceName,terminal,aliases,kind,reason);
record.classification="ao_owned_stimulation";
record.stimulation_capable=true;
record.neutral_value=neutralValue;
record.neutral_source=string(neutralSource);
record.owner=runtimeOwner;
end

function value=owner(onePhoton,twoPhoton)
% Keyed by modality rather than by protocol string so the field names stay
% legal MATLAB identifiers; account_stimulation_outputs maps "1p_dmd" and
% "2p_spiral" onto them.
value=struct("one_photon",string(onePhoton),"two_photon",string(twoPhoton));
end

function record=inherited(role,deviceName,terminal,aliases,kind,reason)
record=base_record(role,deviceName,terminal,aliases,kind,reason);
record.classification="inherited_non_stimulation";
record.stimulation_capable=false;
record.neutral_value=[];
record.neutral_source="";
record.owner=owner("operator","operator");
end

function record=infrastructure(role,deviceName,terminal,aliases,kind,reason)
record=base_record(role,deviceName,terminal,aliases,kind,reason);
record.classification="expected_luminos_infrastructure";
record.stimulation_capable=false;
record.neutral_value=[];
record.neutral_source="";
record.owner=owner("luminos","luminos");
end

function record=unresolved(role,deviceName,terminal,aliases,kind,reason)
record=base_record(role,deviceName,terminal,aliases,kind,reason);
record.classification="unresolved";
% Unknown, and deliberately not false: nothing has established that this
% output cannot stimulate the preparation.
record.stimulation_capable=missing;
record.neutral_value=[];
record.neutral_source="";
record.owner=owner("unknown","unknown");
end

function value=tidy(reason)
% The declarations above wrap over several lines and MATLAB keeps whatever
% spacing that left behind. Collapse it, so the reason reads as a sentence
% wherever it is printed or archived.
value=strip(regexprep(strjoin(string(reason)," "),"\s+"," "));
end

function record=base_record(role,deviceName,terminal,aliases,kind,reason)
record=struct("role",string(role),"device_name",string(deviceName), ...
    "terminal",string(terminal), ...
    "aliases",{reshape(string(aliases),1,[])},"kind",string(kind), ...
    "reason",tidy(reason));
end
