function profile=virtual_upright_2p_profile()
%VIRTUAL_UPRIGHT_2P_PROFILE First-pass VU Chameleon scanner declaration.
profile=struct;
profile.schema_version="0.1.0";
profile.profile_id="virtual_upright_chameleon_spiral";
profile.evidence_acquisition="20260728/1454092P_test";
profile.daq=struct("clock_source","Internal Dev1","sample_rate_hz",200000, ...
    "default_trigger",["Dev1/PFI9","Dev2/PFI1"], ...
    "clock_bridge",["Dev1/PFI12","Dev2/PFI0"],"requires_self_trigger",true);
profile.scanner=struct("name","Chameleon (To friends: Ben)", ...
    "x_port","Dev2/ao0","y_port","Dev2/ao1", ...
    "feedback_x_port","Dev2/ai1","feedback_y_port","Dev2/ai2", ...
    "command_bounds_v",[-5 5],"sample_rate_hz",200000, ...
    "transform_direction","galvo_volts_to_camera_pixels");
profile.modulator=struct("name","2P mod","port","Dev1/ao3", ...
    "minimum_v",0,"maximum_v",5,"dark_v",0);
profile.safety=struct( ...
    "provisional_maximum_velocity_v_per_s",30, ...
    "provisional_maximum_acceleration_v_per_s2",1800, ...
    "limits_are_hardware_validated",false, ...
    "tracking_feedback_required_for_release",true, ...
    "feedback_validated",false, ...
    "live_output_released",false, ...
    "note","The reference acquisition contains AO commands but no galvo-feedback AI task.");
end
